[VIRTUAL-SENSOR]
algo_type       virtual
sensors         pa-therm0-usr  quiet-therm-usr  sm5602_bat  sdm-skin-therm-usr
weight          331            832              37          -223
polling         2000
weight_sum      1000
compensation    -507

[ARVR-SS-CPU0]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1708800  1478400  1324800

[ARVR-SS-CPU1]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu1
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1708800  1478400  1324800

[ARVR-SS-CPU2]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu2
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1708800  1478400  1324800

[ARVR-SS-CPU3]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu3
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1708800  1478400  1324800

[ARVR-SS-CPU4]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu4
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1708800  1478400  1324800

[ARVR-SS-CPU5]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu5
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1708800  1478400  1324800

[ARVR-SS-CPU6]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu6
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1804800  1651200  1401600

[ARVR-SS-CPU7]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu7
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1804800  1651200  1401600

[ARVR-MONITOR-BAT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          battery
polling         2000
trig            32000  36500  37500  39000  40000  41500  43000  44000
clr             30000  35000  37000  38000  39000  40000  41500  43000
target          0500   0601   0703   0804   0905   1207   1313   1414

[ARVR-MONITOR-TEMP_STATE]
algo_type       monitor
sensor          xo-therm-usr
device          temp_state
polling         1000
trig            57000
clr             55000
target          5

[ARVR-MONITOR-5G_TO_4G]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          modem_limit
polling         2000
trig            45000
clr             43000
target          1

[ARVR-MONITOR-CL-BACKLIGHT]
algo_type       monitor
sensor          backlight_therm
device          backlight_therm
polling         1000
trig            42000    44000    46000    49000    51000
clr             40000    42000    44000    46000    49000
target          615      1434     1842     2457     3276

[ARVR-MONITOR-BOOST_LIMIT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          boost_limit
polling         1000
trig            55000
clr             53000
target          1

[ARVR-MONITOR-GPU]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          gpu
polling         1000
trig            49000            52000            55000
clr             46000             49000             52000
target          2       3       4
