[VIRTUAL-SENSOR]
algo_type       virtual
sensors         pa-therm0-usr  quiet-therm-usr  sm5602_bat  sdm-skin-therm-usr
weight          331            832              37          -223
polling         2000
weight_sum      1000
compensation    -507

[NL-SS-CPU0]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0
polling         2000
trig            55000
clr             53000
target          691200

[NL-SS-CPU1]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu1
polling         2000
trig            55000
clr             53000
target          691200

[NL-SS-CPU2]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu2
polling         2000
trig            55000
clr             53000
target          691200

[NL-SS-CPU3]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu3
polling         2000
trig            55000
clr             53000
target          691200

[NL-SS-CPU4]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu4
polling         2000
trig            55000
clr             53000
target          691200

[NL-SS-CPU5]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu5
polling         2000
trig            55000
clr             53000
target          691200

[NL-SS-CPU6]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu6
polling         2000
trig            55000
clr             53000
target          691200

[NL-SS-CPU7]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu7
polling         2000
trig            55000
clr             53000
target          691200

[NL-MONITOR-BAT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          battery
polling         2000
trig            20000  28000  45000
clr             18000  26000  44000
target          1414   1515   1515

[NL-MONITOR-TEMP_STATE]
algo_type       monitor
sensor          xo-therm-usr
device          temp_state
polling         2000
trig            44000	56000
clr             41000	55000
target          100002	12400001

[NL-MONITOR-5G_TO_4G]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          modem_limit
polling         2000
trig            45000
clr             43000
target          1

[NL-MONITOR-GPU]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          gpu
polling         2000
trig            53000
clr             50000
target          1

[NL-MONITOR-FLASH]
algo_type       monitor
sensor          camera-therm-usr
device          temp_state
polling         2000
trig            57000
clr             55000
target          10100004
