[VIRTUAL-SENSOR]
algo_type	virtual
sensors		quiet_therm	battery
weight		3		1
polling		1000

[CAMERA-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		500
trig		39000		40000		41000		47000		48000		55000
clr		38000		39000		40000		46000		47000		49000
target		2169600		1843200		1555200		1094400		806400		652800

[CAMERA-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		34000	36000	38000	39000	60000
clr		33000	34000	36000	38000	48000
target		0       400     1300	1408    1515

[CAMERA-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		53000
clr		48000
target		5

[CAMERA-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		1000
trig		55000
clr		52000
target		1

[CAMERA-MONITOR-BCL]
algo_type	monitor
sensor		bat_soc
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		5
clr		6
target		1+1
reverse		1

[CAMERA-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		48000		50000		53000
clr		46000		48000		50000
target		0	1	2

[CAMERA-MONITOR-CCC_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu5+hotplug_cpu6+hotplug_cpu7+backlight
polling		1000
trig		53000
clr		48000
target		1+1+1+1536
