[GLOBAL-MGAME-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		2000
trig		52000
clr		50000
target		710400

[GLOBAL-MGAME-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		2000
trig		52000
clr		50000
target		844800

[GLOBAL-MGAME-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		35000	37000	39000	40000	42000	44000	46000
clr		32000	35000	37000	39000	41000	43000	44000
target		101	202	803	906	909	1313	1515

[GLOBAL-MGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		46000		48000		51000		53000
clr		44000		46000		50000		51000
target		10100000	10100004	12300001	12520001

[GLOBAL-MGAME-MONITOR-FLASH]
algo_type       monitor
sensor          flash_therm
device          temp_state
polling         2000
trig            65000
clr             60000
target          10100004

[GLOBAL-MGAME-MONITOR-CCC]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling         2000
trig            55000
clr             53000
target          1+1+1+1

[GLOBAL-MGAME-MONITOR-BOOST_LIMIT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          boost_limit
polling         2000
trig            54000
clr             51000
target          1

[GLOBAL-MGAME-MONITOR-BCL]
algo_type       monitor
sensor          BAT_SOC
device          cpu0+hotplug_cpu1+hotplug_cpu2+hotplug_cpu3
polling         2000
trig            5
clr             6
target          1075200+1+1+1
reverse         1

[GLOBAL-MGAME-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		52000
clr		50000
target		4

[GLOBAL-MGAME-MONITOR-BACKLIGHT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          backlight-clone
polling         2000
trig            39000    40500    42000    45000
clr             37000    39000    40500    43000
target          2048	 2273	  2601	   2908

[GLOBAL-MGAME-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		market_download_limit
polling		2000
trig		40000
clr		37000
target		1
