[TGAME-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		2000
trig		53000
clr			51000
target		659000

[TGAME-SS-CPU4]
algo_type   ss
sensor      VIRTUAL-SENSOR
device      cpu4
polling     2000
trig        53000
clr         51000
target      437000

[TGAME-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		32000		37000		39000		41000		42000		43000		45000		48000		60000
clr			30000		35000		37000		39000		41000		42000		43000		45000		48000
target		300			401			502			903			1203		1304		1409		1414		1515

[TGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		46000			52000		54000
clr			45000			50000		53000
target		10100004		12400001	12500001

[TGAME-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		2000
trig		5
clr			6
target		1162000+1+1
reverse		1

[TGAME-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		53000
clr			50000
target		40

[TGAME-MONITOR-HBM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_hbm_disabled
polling		2000
trig		40000
clr			38000
target		1

[TGAME-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		brightness0-clone
polling		2000
trig		37000	39000	41000	43000	46000
clr			35000	37000	39000	41000	43000
target		2048	4096	4914	5546	6447

[TGAME-MONITOR-MODEM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		mtk-cl-scg-off
polling		2000
trig		49000
clr		48000
target		1

