[NL-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		2000
trig		55000
clr			53000
target		700000

[NL-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		2000
trig		55000
clr			53000
target		921000

[NL-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		32000		35000		37000		38000		39000		41000		43000		45000		48000
clr			30000		34000		35000		37000		38000		39000		41000		43000		45000
target		300			401			401			902			1203			1204			1210			1411			1414			1515

[NL-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		51000
clr			49000
target		12400001

[NL-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr			6
target		1+1
reverse		1

[NL-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		55000
clr			53000
target		20