[HUANJI-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		2000
trig		47000		47800
clr		46000		47000
target		1075200		300000

[HUANJI-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		2000
trig		41000		43000		45000		46000		47000		47500		47800
clr		39000		41000		43000		45000		46000		47000		47500
target		2150400		1862400		1766400		1670400		1075200		825600		710400

[HUANJI-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		2000
trig		41000		43000		45000		46000		47000		47500		47800
clr		39000		41000		43000		45000		46000		47000		47500
target		2361600		2169600		1862400		1670400		1075200		960000		844800

[HUANJI-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		10000
trig		25000		40000
clr		20000		39000
target		1414		1515

[HUANJI-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		10000
trig		43000		50000		51000
clr		41000		48000		50000
target		10100000	12400001	12500001

[HUANJI-MONITOR-FLASH]
algo_type	monitor
sensor		flash_therm
device		temp_state
polling		10000
trig		70000
clr		65000
target		10100004

[HUANJI-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling		10000
trig		54000
clr		52000
target		1+1+1+1

[HUANJI-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		10000
trig		54000
clr		51000
target		1

[HUANJI-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		10000
trig		5
clr		6
target		1286400+1+1
reverse		1

[HUANJI-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		10000
trig		54000
clr		52000
target		4

[HUANJI-MODEM-HBM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal-hbm-disabled
polling		10000
trig		39000
clr		37000
target		1

[HUANJI-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight-clone
polling		10000
trig		37000		39000		41000
clr		35000		37000		39000
target		2458		3072		3440

[HUANJI-MODEM-UL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_ul
polling		10000
trig		46000
clr		43000
target		1

[HUANJI-MODEM-DL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_dl
polling		10000
trig		46000
clr		43000
target		1

[HUANJI-MONITOR-PARALLEL-TO-SERIAL]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          market_download_limit
polling         10000
trig            40000
clr             38000
target          1
