[CAMERA-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR1
device		cpu0
polling		2000
trig		31000		49500
clr		29000		48000
target		1363200        1094400

[CAMERA-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR1
device		cpu4
polling		2000
trig		46000		47000		48000		49500		52000		53000		54000
clr		44000		46000		47000		48000		50500		52000		53000
target		1651200		1555200 	1382400		1382400		1382400        1132800        652800

[CAMERA-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR1
device		cpu7
polling		2000
trig		46000		47000		48000		49500		52000		53000		54000
clr		44000		46000		47000		48000		50500		52000		53000
target		1612800		1401600 	1286400		940800		940800         768000         768000

[CAMERA-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR1
device		battery
polling		2000
trig		32000	37000	38000    39000
clr		30000	36000	37000    38000
target		1008	1209	1412     1515

[CAMERA-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR1
device		temp_state
polling		2000
trig		47000            48000          51000
clr		46000            47000          48000
target	        12300004         12400004       12500001

[CAMERA-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR1
device		hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling		2000
trig		55000
clr		53000
target		1+1+1

[CAMERA-MONITOR-FLASH]
algo_type	monitor
sensor		flash_therm
device		temp_state
polling		2000
trig		63000
clr		60000
target		10100004

[CAMERA-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR1
device		boost_limit
polling		2000
trig		54000
clr		52000
target		1

[CAMERA-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		2000
trig		5
clr		6
target		1132800+1+1
reverse		1

[CAMERA-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR1
device		gpu
polling		2000
trig		53000
clr		51000
target		2

[CAMERA-MONITOR-BACKLIGHT]
algo_type       monitor
sensor          VIRTUAL-SENSOR1
device          backlight-clone
polling         2000
trig            37000    39000    41000    43000    46000
clr             35000    37000    39000    41000    43000
target          150	 100	  80	   50       32

[CAMERA-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor		VIRTUAL-SENSOR1
device		market_download_limit
polling		2000
trig		40000
clr		37000
target		1

[CAMERA-MONITOR-MODEM-5GTO4G]
algo_type	monitor
sensor		VIRTUAL-SENSOR1
device		modem_limit
polling		2000
trig		45000
clr		43000
target		1

[CAMERA-MONITOR-WIFI-LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR1
device	wifi_limit
polling	2000
trig	25000
clr	23000
target	1
