[ARVR-SS-CPU0]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu0
polling	2000
trig	49000
clr	47000
target	1400000

[ARVR-SS-CPU4]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu4
polling	2000
trig	40000	55000
clr	38000	53000
target	1400000	600000

[ARVR-SS-CPU7]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu7
polling	2000
trig	40000	55000
clr	38000	53000
target	1700000	800000

[ARVR-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	battery
polling	2000
trig	35200	35700	36200	37200	37700	39800	40100	41000
clr	34800	35200	35700	36200	37200	39100	39800	40100
target	101	202	505	707	1010	1111	1313	1515

[ARVR-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	temp_state
polling	2000
trig	45000	48000	50000	51000	53000
clr	43000	45000	48000	50000	51000
target	110100000	110100004	110300001	112310001	112520001

[ARVR-MONITOR-FLASH]
algo_type	monitor
sensor	flash_therm
device	temp_state
polling	2000
trig	65000
clr	60000
target	110100004

[ARVR-MONITOR-CCC]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling	2000
trig	55000
clr	53000
target	1+1+1

[ARVR-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	boost_limit
polling	2000
trig	55000
clr	53000
target	1

[ARVR-MONITOR-BCL]
algo_type	monitor
sensor	BAT_SOC
device	hotplug_cpu3+hotplug_cpu7
polling	2000
trig	5
clr	6
target	1+1
reverse	1

[ARVR-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	gpu
polling	2000
trig	38000	55000
clr	36000	54000
target	1	2

[ARVR-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	thermal_max_brightness
polling	2000
trig	51000
clr	49000
target	160

[ARVR-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	market_download_limit
polling	2000
trig	40000
clr	37000
target	1
