[ARVR-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		500
trig		16000
clr		15000
target		1497600

[ARVR-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		36500	37500	38300	39000	39700	41700	43000	45000	60000
clr		36000	36900	37500	38300	39000	39700	41700	43000	58000
target	     	500	604	705	806	907	1109	1211	1412	1515

[ARVR-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		51000		56000
clr		50000		55000
target		10100004	12400001

[ARVR-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		1000
trig		16000
clr		15000
target		1

[ARVR-MONITOR-BCL]
algo_type	monitor
sensor		bat_soc
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		5
clr		6
target		1+1
reverse		1

[ARVR-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		16000
clr		15000
target		2
