[INDIA-MGAME-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		1000
trig		19000		55000
clr		18000		53000
target		1862400       710400

[INDIA-MGAME-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		37000	38300	39200	40700	41700	43000	44000	46000	60000
clr		36300	37700	38300	39200	40700	41700	43000	44000	58000
target		700	805	807	908	1009	1109	1210	1411	1515

[INDIA-MGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		45000           55000
clr		43000           48000
target		10100000        12400001

[INDIA-MGAME-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		2000
trig		5
clr		6
target		1286400+1+1
reverse		1

[INDIA-MGAME-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		54000
clr		51000
target		2

[INDIA-MGAME-MONITOR-HBM]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          thermal_hbm_disabled
polling         2000
trig            40000
clr             38000
target          1

[INDIA-MGAME-MONITOR-BACKLIGHT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          backlight
polling         2000
trig            43000
clr             40000
target          573
