[MGAME-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		1000
trig		48000		50000
clr		46000		49000
target		1209600	691200

[MGAME-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		1000
trig		48000		50000
clr		46000		49000
target		1267200	806400

[MGAME-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		37000	38300	39200	40700	41700	43000	44000	46000	60000
clr		36300	37700	38300	39200	40700	41700	43000	44000	58000
target		700	805	807	908	1209	1209	1410	1414	1515

[MGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		42000		52000
clr		40000		50000
target		10100000	12400001

[MGAME-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		2000
trig		5
clr		6
target		1286400+1+1
reverse		1

[MGAME-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		48000		50000
clr		46000		49000
target		2	3

[MGAME-MONITOR-HBM]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          thermal_hbm_disabled
polling         2000
trig            39000
clr             37000
target          1

[MGAME-MONITOR-BACKLIGHT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          backlight
polling         2000
trig            41000	43000	46000
clr             38000	42000	44000
target          390	1000	1377
