[IEC-HUANJI-SS-CPU0]
algo_type	ss
sensor	VIRTUAL-SENSOR0
device	cpu0
polling	1000
trig	31000	48000
clr	29000	44000
target	1075200	614400

[IEC-HUANJI-SS-CPU4]
algo_type	ss
sensor	VIRTUAL-SENSOR0
device	cpu4
polling	1000
trig	31000	36000	38000	41000	45000	46000	48500
clr	29000	31000	36000	38000	43000	45000	47000
target	1881600	1766400	1555200	1324800	1209600	1113600	633600

[IEC-HUANJI-SS-CPU7]
algo_type	ss
sensor	VIRTUAL-SENSOR0
device	cpu7
polling	1000
trig	31000	36000	38000	41000	45000	46000	48500
clr	29000	31000	36000	38000	43000	45000	47000
target	1843200	1728000	1497600	1286400	1171200	1056000	806400

[IEC-HUANJI-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	battery
polling	2000
trig	25000	40000
clr	20000	38000
target	1414	1515

[IEC-HUANJI-MONITOR-WIRELESS]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	wireless_charge
polling	2000
trig	25000	40000
clr	20000	38000
target	1414	1515

[IEC-HUANJI-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	temp_state
polling	2000
trig	30000	46000	47000	52000
clr	28000	45000	46000	50000
target	10100000	12310004	12520001	12520001

[IEC-HUANJI-MONITOR-FLASH]
algo_type	monitor
sensor	flash_therm
device	temp_state
polling	2000
trig	65000
clr	60000
target	10100004

[IEC-HUANJI-MONITOR-CCC]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	hotplug_cpu7
polling	2000
trig	49000
clr	48000
target	1

[IEC-HUANJI-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	boost_limit
polling	2000
trig	54000
clr	51000
target	1

[IEC-HUANJI-MONITOR-BCL]
algo_type	monitor
sensor	BAT_SOC
device	cpu4+hotplug_cpu2+hotplug_cpu3+hotplug_cpu7
polling	2000
trig	5
clr	6
target	1209600+1+1+1
reverse	1

[IEC-HUANJI-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	gpu
polling	2000
trig	41000	43000	45000	48000
clr	39000	41000	43000	45000
target	1	2	3	4

[IEC-HUANJI-MONITOR-HBM]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	thermal-hbm-disabled
polling	2000
trig	39000
clr	37000
target	1


[IEC-HUANJI-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	backlight-clone
polling	2000
trig	35000	42000
clr	30000	40000
target	22	10

[IEC-HUANJI-MODEM-UL]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	modem-ul
polling	2000
trig	46000
clr	43000
target	1

[IEC-HUANJI-MODEM-DL]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	modem-dl
polling	2000
trig	46000
clr	43000
target	1

[IEC-HUANJI-MODEM-5GTO4G]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	modem_limit
polling	2000
trig	45000
clr	43000
target	1

[IEC-HUANJI-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	market_download_limit
polling	2000
trig	40000
clr	37000
target	1

[IEC-HUANJI-SS-LMH_CPU4]
algo_type	ss
sensor	VIRTUAL-SENSOR0
device	lmh_cpu4
polling	1000
trig	25000
clr	23000
target	1

[IEC-HUANJI-SS-LMH_CPU7]
algo_type	ss
sensor	VIRTUAL-SENSOR0
device	lmh_cpu7
polling	1000
trig	25000
clr	23000
target	1