#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

from hico_thermal.table import build_thermal_table, write_thermal_table


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="hico-table-test-") as td:
        root = Path(td)
        mapped = root / "database/mapped/devices/test/device-a"
        mapped.mkdir(parents=True)
        (mapped / "thermal.json").write_text(
            json.dumps(
                {
                    "schema": "hico.artifact-map.v3",
                    "root": "devices/test/device-a/thermal",
                    "artifacts": [
                        {
                            "name": "thermal.conf",
                            "path": "devices/test/device-a/thermal/thermal.conf",
                            "format": "thermal-engine-text",
                            "codec": "plain",
                            "parser": "thermal-engine-text-v2",
                            "decode_status": "plain",
                            "max_trip_c": 48.0,
                            "shutdown_c": 105.0,
                            "sha256": "a" * 64,
                        }
                    ],
                    "failures": [],
                }
            )
            + "\n"
        )
        tuned = root / "devices/test/device-a/tuned"
        tuned.mkdir(parents=True)
        (tuned / "TEMPLATE.md").write_text(
            "# Thermal template\n\n"
            "Platform `test`, policy **generic**, margin 4 °C. Generated by `tools/tune_thermal.py`.\n\n"
            "| File | Section | Limits | Sensor | Stock trips | Tuned trips |\n"
            "|---|---|---|---|---|---|\n"
            "| thermal.conf | CPU | `cpu0` | `soc` | 40 44 48 | 44 48 52 |\n"
        )
        table = build_thermal_table(root)
        assert table["summary"]["artifact_rows"] == 1
        assert table["summary"]["tuning_rows"] == 1
        assert table["tuning"][0]["original_max_trip_c"] == 48.0
        assert table["tuning"][0]["hico_candidate_max_trip_c"] == 52.0
        assert table["tuning"][0]["delta_c"] == 4.0
        assert table["artifacts"][0]["hico_candidate_max_trip_c"] == 52.0
        output = root / "out"
        write_thermal_table(root, output)
        for name in ("thermal.json", "thermal-artifacts.csv", "thermal-tuning.csv", "THERMAL_TABLE.md"):
            assert (output / name).is_file(), name
    print("HiCo thermal table tests: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
