[VIRTUAL-SENSOR]
algo_type	virtual
sensors		mtktsAP
weight		1
polling		1000

[CLASS0-SS-CPU0]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0
polling         500
trig            52000            54000
clr             50000             52000
target          1500000	1500000

[CLASS0-SS-CPU6]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu6
polling         500
trig            52000            54000
clr             50000             52000
target          1532000	1295000

[CLASS0-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig    	36000	37000	38000	39000	40000	41000	42000	43000	44000	45000
clr     	35000	36000	37000	38000	39000	40000	41000	42000	43000	44000
target		3100	3200	3300	3400	3500	3600	3700	3800	3900	4000

[CLASS0-MONITOR-TEMP_STATE]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          temp_state
polling         1000
trig            56000
clr             54000
target          2400004

[CLASS0-MONITOR-MTK-CL-BACKLIGHT]
algo_type       monitor
sensor          backlight_therm
device          mtk-cl-backlight
polling         2000
trig            39000	41000	43000	46000
clr             34000	39000	41000	44000
target          80	65	50	45

[CLASS0-MONITOR-GPU]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          gpu
polling         1000
trig            49000            52000            55000
clr             46000             49000             52000
target          2       4       6
