[TGAME-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		1000
trig		55000
clr		53000
target		710400

[TGAME-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		1000
trig		55000
clr		53000
target		844800

[TGAME-MONITOR-BAT]
algo_type	monitor
sensor		battery
device		battery
polling		2000
trig		38000		39000		40000		42000		43000		44000		45000		47000		51000
clr		36000		38000		39000		40000		42000		43000		44000		45000		47000
target		101		202		303		404		707		808		909		1010		1414

[TGAME-MONITOR-FLASH]
algo_type	monitor
sensor		flash_therm
device		temp_state
polling		2000
trig		57000
clr		56000
target		10100004

[TGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		TEMP_VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		52000
clr		50000
target		12400001

[TGAME-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		2000
trig		5
clr		6
target		1286400+1+1
reverse		1

[TGAME-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		51000
clr		49000
target		2

[TGAME-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		backlight_therm
device		backlight
polling		2000
trig		39000		41000		43000		46000
clr		37000		39000		41000		44000
target		447		797		1022		1237

[TGAME-MODEM-UL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_ul
polling		2000
trig		48000
clr		43000
target		1

[TGAME-MODEM-DL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_dl
polling		2000
trig		48000
clr		43000
target		1
