[BAT_SOC]
algo_type	simulated
path	/sys/class/power_supply/battery/capacity
polling	10000

[VIRTUAL-SENSOR0]
algo_type	Virtual
sensors	quiet_therm	pa_therm0	pa_therm1	wifi_therm	cpu_therm	battery	charger_therm0
weight	440	-87	49	-35	263	200	88
polling	2000
weight_sum	1000
compensation	2200

[PER-NORMAL-MONITOR-SENSOR]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	VIRTUAL-SENSOR0
polling	2000
trig	25000	30000	35000
clr	23000	27000	32000
target	10000	5000	1000

[PER-NORMAL-SS-CPU4]
algo_type	ss
sensor	VIRTUAL-SENSOR0
device	cpu4
polling	2000
trig	43000	45000	46000	47000	50000	53000
clr	41000	44000	45000	46000	48000	51000
target	1900800	1497600	1344000	1190400	960000	691200

[PER-NORMAL-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	battery
polling	2000
trig	34000	36500	37500	38500	39200	40500	41800	44000	45000
clr	32000	35000	36500	37500	38500	39200	41000	43000	44000
target	900	1002	1003	1204	1505	1507	1508	1511	1515

[PER-NORMAL-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	temp_state
polling	2000
trig	45000	48000	50000	51000	53000
clr	43000	46000	48000	50000	52000
target	110100000	110100000	110300000	112310004	112520004

[PER-NORMAL-MONITOR-FLASH]
algo_type	monitor
sensor	flash_therm
device	temp_state
polling	2000
trig	60000
clr	57000
target	110100004

[PER-NORMAL-MONITOR-CCC]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	hotplug_cpu0+hotplug_cpu6+hotplug_cpu7
polling	2000
trig	55000
clr	53000
target	1+1+1

[PER-NORMAL-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	boost_limit
polling	2000
trig	53000
clr	50000
target	1

[PER-NORMAL-MONITOR-BCL]
algo_type	monitor
sensor	BAT_SOC
device	cpu0+cpu4+hotplug_cpu3+hotplug_cpu6+hotplug_cpu7
polling	2000
trig	1	5
clr	2	6
target	940800+1344000+1+1+1	1113600+2400000+0+1+1
reverse	1

[PER-NORMAL-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	gpu
polling	2000
trig	48000	50000	53000
clr	46000	48000	52000
target	2	5	8

[PER-NORMAL-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	thermal_max_brightness
polling	2000
trig	51000
clr	49000
target	160

[PER-NORMAL-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	market_download_limit
polling	2000
trig	40000
clr	37000
target	1

[PER-NORMAL-MONITOR-MODEM-5GTO4G]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	modem_limit
polling	20000
trig	47000
clr	43000
target	1

[PER-NORMAL-MONITOR-TORCH-LIMIT]
algo_type	monitor
sensor	flash_therm
device	torch_level
polling	2000
trig	53000	57000
clr	50000	54000
target	1	2

[PER-NORMAL-MONITOR-WIFI-LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	wifi_limit
polling	2000
trig	46000
clr	44000
target	1