[VIRTUAL-SENSOR]
algo_type	virtual
sensors		mtktsAP
weight		1
polling		1000

[SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		2000
trig		48000
clr		    46000
target		1866000

[SS-CPU0-1]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		2000
trig		50000
clr		    48000
target		1666000

[SS-CPU0-2]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		2000
trig		52000
clr		    50000
target		1375000

[SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		2000
trig		49000
clr		    47000
target		1860000

[SS-CPU6-1]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		2000
trig		51000
clr		    49000
target		1670000

[SS-CPU6-2]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		2000
trig		53000
clr		    51000
target		1419000

[MONITOR-CPU5]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu5
polling		1000
trig		49000
clr			47000
target		1

[MONITOR-CPU3]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu3
polling		1000
trig		51000
clr			49000
target		1

[MONITOR-CPU2]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu2
polling		1000
trig		53000
clr			51000
target		1

[MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		26000	61000
clr		    25000	60000
target		1412	1512

[MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		58000
clr		    55000
target		1

[MONITOR-CCC_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		61000
clr		    58000
target		1+1

[MONITOR-CPU_HOTPLUG]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu0+hotplug_cpu1+hotplug_cpu2+hotplug_cpu3+hotplug_cpu4+hotplug_cpu5+hotplug_cpu7
polling		1000
trig		55000
clr		    52000
target		1+1+1+1+1+1+1

[MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		55000
clr		    53000
target		3

[MONITOR-CPU_HOTPLUG-1]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu1+hotplug_cpu7+hotplug_cpu0
polling		1000
trig		55000
clr			53000
target		1+1+1