[NOLIMITS-SS-CPU4]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu4
polling	2000
trig	55000
clr	53000
target	633600

[NOLIMITS-SS-CPU7]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu7
polling	1000
trig	55000
clr	53000
target	787200

[NOLIMITS-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	battery
polling	2000
trig	37000	39000	40000	41000	43000
clr	35000	38000	39000	40000	42000
target	101	303	404	505	1515

[NOLIMITS-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	temp_state
polling	2000
trig	45000	52000	53000
clr	43000	50000	52000
target	10100000	12510001	12520001

[NOLIMITS-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	gpu
polling	2000
trig	55000
clr	54000
target	1

[NOLIMITS-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	backlight-clone
polling	2000
trig	39000	41000	43000	46000
clr	37000	39000	41000	43000
target	100	89	73	58

[NOLIMITS-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	market_download_limit
polling	2000
trig	40000
clr	37000
target	1
