[GLOBAL-NOLIMITS-SS-CPU0]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu0
polling	1000
trig	54000	55000
clr	53000	54000
target	500000	200000

[GLOBAL-NOLIMITS-SS-CPU4]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu4
polling	1000
trig	54000	55000
clr	53000	54000
target	500000	200000

[GLOBAL-NOLIMITS-SS-CPU7]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu7
polling	1000
trig	55000
clr	54000
target	1300000

[GLOBAL-NOLIMITS-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	battery
polling	2000
trig	36200	37100	38000	39000	39800	42000	43000	45000
clr	35000	36300	37200	38000	39000	41000	42000	43500
target	404	505	505	606	808	1111	1514	1515

[GLOBAL-NOLIMITS-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	temp_state
polling	2000
trig	50000	51000
clr	49000	50000
target	12400001	12500001

[GLOBAL-NOLIMITS-MONITOR-FLASH]
algo_type	monitor
sensor	flash_therm
device	temp_state
polling	2000
trig	60000
clr	55000
target	10100004

[GLOBAL-NOLIMITS-MONITOR-BCL]
algo_type	monitor
sensor	BAT_SOC
device	hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling	2000
trig	5
clr	6
target	1+1+1
reverse	1

[GLOBAL-NOLIMITS-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	gpu
polling	2000
trig	19000
clr	17000
target	5

[GLOBAL-NOLIMITS-MONITOR-HBM]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	thermal-hbm-disabled
polling	2000
trig	39000
clr	37000
target	1

[GLOBAL-NOLIMITS-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	backlight-clone
polling	2000
trig	39000	41000	43000	46000
clr	37000	39000	41000	43000
target	100	86	70	56