[GLOBAL-PHONE-SS-CPU0]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu0
polling	1000
trig	39000
clr	37000
target	1400000

[GLOBAL-PHONE-SS-CPU4]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu4
polling	1000
trig	29000	49000
clr	27000	48000
target	1500000	500000

[GLOBAL-PHONE-SS-CPU7]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu7
polling	1000
trig	29000	49000
clr	27000	48000
target	1500000	500000

[GLOBAL-PHONE-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	battery
polling	2000
trig	15000
clr	14000
target	1515

[GLOBAL-PHONE-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	temp_state
polling	2000
trig	45000	49000	50000	51000
clr	43000	48000	49000	50000
target	10100000	12300004	12400001	12500001

[GLOBAL-PHONE-MONITOR-FLASH]
algo_type	monitor
sensor	flash_therm
device	temp_state
polling	2000
trig	60000
clr	55000
target	10100004

[GLOBAL-PHONE-MONITOR-CCC]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	hotplug_cpu6+hotplug_cpu7
polling	2000
trig	52000
clr	51000
target	1+1

[GLOBAL-PHONE-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	boost_limit
polling	2000
trig	52000
clr	49000
target	1

[GLOBAL-PHONE-MONITOR-BCL]
algo_type	monitor
sensor	BAT_SOC
device	hotplug_cpu6+hotplug_cpu7
polling	2000
trig	5
clr	6
target	1+1
reverse	1

[GLOBAL-PHONE-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	gpu
polling	2000
trig	47000	49000	52000
clr	45000	47000	51000
target	10	20	39

[GLOBAL-PHONE-MONITOR-HBM]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	thermal-hbm-disabled
polling	2000
trig	39000
clr	37000
target	1

[GLOBAL-PHONE-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	backlight-clone
polling	2000
trig	39000	41000	43000	46000
clr	37000	39000	41000	43000
target	100	86	70	56

[GLOBAL-PHONE-MONITOR-MODEM]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	mtk-cl-scg-off
polling	2000
trig	49000
clr	48000
target	1