[YUANSHEN-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		2000
trig		54000
clr		51000
target		1056000

[YUANSHEN-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		2000
trig		54000
clr		51000
target		883200

[YUANSHEN-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		2000
trig		54000
clr		51000
target		787200

[YUANSHEN-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		35000	37000	39000	40000	44000	45000
clr		32000	35000	37000	39000	42000	44000
target		101	202	808	909	1212	1515

[YUANSHEN-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		47000	48000	51000	53000
clr		45000	47000	49000	51000
target		110100000	110100004	112300001	112520001

[YUANSHEN-MONITOR-FLASH]
algo_type	monitor
sensor		flash_therm
device		temp_state
polling		2000
trig		65000
clr		60000
target		110100004

[YUANSHEN-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu2+hotplug_cpu3+hotplug_cpu7
polling		2000
trig		55000
clr		53000
target		1+1+1

[YUANSHEN-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		54000
clr		51000
target		1

[YUANSHEN-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu2+hotplug_cpu3+hotplug_cpu7
polling		2000
trig		5
clr		6
target		1209600+1+1+1
reverse		1

[YUANSHEN-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		54000
clr		51000
target		4

[YUANSHEN-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_max_brightness
polling		2000
trig		51000
clr		49000
target		160

[YUANSHEN-SS-LMH_CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		lmh_cpu4
polling		1000
trig		25000
clr		23000
target		1

[YUANSHEN-SS-LMH_CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		lmh_cpu7
polling		1000
trig		25000
clr		23000
target		1

[YUANSHEN-REVERSE_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_reverse_limit
polling		2000
trig		34000
clr		32000
target		2
