[NOLIMITS-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		2000
trig		54000
clr		51000
target		1056000

[NOLIMITS-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		2000
trig		55000
clr		53000
target		633600

[NOLIMITS-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		1000
trig		55000
clr		53000
target		787200

[NOLIMITS-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		37000	39000	40000	41000	43000
clr		35000	37000	39000	40000	41000
target		101	303	404	505	1515

[NOLIMITS-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		51000		53000
clr		49000		51000
target		112300001	112520001

[NOLIMITS-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		55000
clr		54000
target		1

[NOLIMITS-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_max_brightness
polling		2000
trig		51000
clr		49000
target		160

[NOLIMITS-MONITOR-REVERSE_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_reverse_limit
polling		2000
trig		34000
clr		32000
target		2
