[VIRTUAL-SENSOR]
algo_type       virtual
sensors         pa-therm0-usr  quiet-therm-usr  sm5602_bat  sdm-skin-therm-usr
weight          331            832              37          -223
polling         2000
weight_sum      1000
compensation    -507

[CAM-SS-SILVER]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0+cpu6
polling         2000
trig            45000            46000            47000            48500            51000
clr             43000             45000             46000             47000             49500
target          1651200+1862400  1516800+1516800  1344000+1324800  940800+1056000  691200+806400

[CAM-MONITOR-GPU]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          gpu
polling         2000
trig            45000            46000            47000
clr             43000             45000             46000
target          0       1       2

[CAM-MONITOR-BAT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          battery
polling         2000
trig            30000  35000  37000
clr             28000  33000  35000
target          1010   1414   1515

[CAM-MONITOR-TEMP_STATE]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          temp_state
polling         2000
trig            46000   48000   51000
clr             44000   46000   50000
target          2000000 2300000 2400001

[CAM-MONITOR-CL-BACKLIGHT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          backlight_therm
polling         2000
trig            41000    43000    46000
clr             39000    41000    44000
target          155      833      1283

[CAM-MONITOR-FLASH]
algo_type       monitor
sensor          camera-therm-usr
device          temp_state
polling         2000
trig            55000
clr             53000
target          10100004
