[VIRTUAL-SENSOR]
algo_type       virtual
sensors         pa-therm0-usr  quiet-therm-usr  sm5602_bat  sdm-skin-therm-usr
weight          331            832              37          -223
polling         2000
weight_sum      1000
compensation    -507

[MGAME-SS-SILVER]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0+cpu6
polling         2000
trig            44000            45000            46000            47000            48000            52000
clr             42000             44000             45000             46000             47000             50000
target          1708800+2054400  1651200+1651200  1328800+1516800  1113600+1228800  940800+940800   691200+691200

[MGAME-MONITOR-GPU]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          gpu
polling         2000
trig            53000
clr             51000
target          2

[MGAME-MONITOR-BAT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          battery
polling         2000
trig            32000  35000  37000  41500  44000  45500
clr             30000  33000  35000  40000  43000  44000
target          0600   0701   0803   0909   1010   1414

[MGAME-MONITOR-TEMP_STATE]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          temp_state
polling         2000
trig            46000   48000   51000
clr             44000   46000   50000
target          2000000 2300000 2400000

[MGAME-MONITOR-CL-BACKLIGHT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          backlight_therm
polling         2000
trig            41000    43000    46000
clr             39000    41000    44000
target          155      833      1283

[MGAME-MONITOR-FLASH]
algo_type       monitor
sensor          camera-therm-usr
device          temp_state
polling         2000
trig            57000
clr             55000
target          10100004
