[VIRTUAL-SENSOR]
algo_type       virtual
sensors         pa-therm0-usr  quiet-therm-usr  sm5602_bat  sdm-skin-therm-usr
weight          331            832              37          -223
polling         2000
weight_sum      1000
compensation    -507

[PHONE-SS-SILVER]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0+cpu6
polling         2000
trig            32000            37000            47000
clr             30000             35000             45000
target          1228800+1324800    940800+1056000  691200+805400

[PHONE-MONITOR-BAT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          battery
polling         2000
trig            20000  45000
clr             18000  44000
target          1313   1313


