[VIRTUAL-SENSOR]
algo_type       virtual
sensors         pa-therm0-usr  quiet-therm-usr  sm5602_bat  sdm-skin-therm-usr
weight          331            832              37          -223
polling         2000
weight_sum      1000
compensation    -507

[VIDEO-SS-SILVER]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0+cpu6
polling         2000
trig            40000            43000            46000            48000            49500            52000
clr             38000             40000             43500             46000             48000             50000
target          1708800+2054400  1651200+1651200  1328800+1516800  1113600+1228800  940800+940800   691200+691200

[VIDEO-MONITOR-GPU]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          gpu
polling         2000
trig            46000            48000            50000
clr             44000             46000             48000
target          0       1       2

[VIDEO-MONITOR-BAT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          battery
polling         2000
trig            32000  35000  36000  37000  39000  41000  43000  44000  45000  48000
clr             30000  34000  35000  36000  38000  39000  41000  43000  44000  45000
target          0804   1004   1006   1008   1010   1012   1014   1015   1415   1515

[VIDEO-MONITOR-TEMP_STATE]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          temp_state
polling         2000
trig            46000   48000   50000
clr             44000   46000   48000
target          2000000 2300000 2400000

[VIDEO-MONITOR-CL-BACKLIGHT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          backlight_therm
polling         2000
trig            41000    43000    46000
clr             39000    41000    44000
target          155      833      1283

[VIDEO-MONITOR-FLASH]
algo_type       monitor
sensor          camera-therm-usr
device          temp_state
polling         2000
trig            57000
clr             55000
target          10100004
