[IEC-NOLIMITS-SS-CPU4]
algo_type	ss
sensor	VIRTUAL-SENSOR0
device	cpu4
polling	1000
trig	55000
clr	54000
target	633600

[IEC-NOLIMITS-SS-CPU7]
algo_type	ss
sensor	VIRTUAL-SENSOR0
device	cpu7
polling	1000
trig	55000
clr	54000
target	806400

[IEC-NOLIMITS-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	battery
polling	2000
trig	20000	40000
clr	18000	38000
target	1313	1515

[IEC-NOLIMITS-MONITOR-WIRELESS]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	wireless_charge
polling	2000
trig	20000	40000
clr	18000	38000
target	1313	1515

[IEC-NOLIMITS-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	temp_state
polling	2000
trig	51000	52000	53000
clr	50000	51000	51000
target	12400001	12510001	12520001

[IEC-NOLIMITS-MONITOR-FLASH]
algo_type	monitor
sensor	flash_therm
device	temp_state
polling	2000
trig	65000
clr	60000
target	10100004

[IEC-NOLIMITS-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	gpu
polling	2000
trig	55000
clr	54000
target	1

[IEC-NOLIMITS-MONITOR-HBM]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	thermal-hbm-disabled
polling	2000
trig	39000
clr	37000
target	1

[IEC-NOLIMITS-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	backlight-clone
polling	2000
trig	37000	39000	41000	43000	46000
clr	35000	37000	39000	41000	43000
target	140	100	80	50	32

[IEC-NOLIMITS-MODEM-UL]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	modem-ul
polling	2000
trig	46000
clr	43000
target	1

[IEC-NOLIMITS-MODEM-DL]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	modem-dl
polling	2000
trig	46000
clr	43000
target	1

[IEC-NOLIMITS-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	market_download_limit
polling	2000
trig	40000	48000
clr	37000	45000
target	1	2