[CAMERA-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		2000
trig        39000        41000        45000        47500
clr         38000         40000         44000         46500
target      1497600  1248000  1017600  768000

[CAMERA-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		2000
trig        39000        41000        45000        47500
clr         38000         40000         44000         46500
target      1708800  1555200  1094400  806400

[CAMERA-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig        20000
clr         18000
target      2424

[CAMERA-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig        42000     45000     49000     49500
clr         40000     43000     48500     49000
target      10100004  12300004  12400001  12500001

[CAMERA-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device      hotplug_cpu4+hotplug_cpu5+hotplug_cpu3+hotplug_cpu6+hotplug_cpu7
polling     2000
trig        47500        48000
clr         46500         47500
target      1+0+0+1+0   1+1+1+0+0


[CAMERA-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig        50000
clr         49000
target      1

[CAMERA-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr	     	6
target		1+1
reverse		1

[CAMERA-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		43000		46000		50000
clr		    42000		    45000		    48000
target		1	     	2	    	3

[CAMERA-MONITOR-HBM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_hbm_disabled
polling		2000
trig		39000
clr		    38000
target		1

[CAMERA-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight
polling		2000
trig        36500  37500  38500  40500  44500
clr         35500  36500  37500  39500  43500
target      287    507    687    897    1337
