[VIDEOCHAT-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		2000
trig        39000        41000        43000        47000        49000
clr         37000         40000         42000         45000         47000
target      1804800  1612800  1248000  1017600  576000

[VIDEOCHAT-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		2000
trig        39000        41000        43000        47000        49000
clr         37000         40000         42000         45000         47000
target      1843200  1708800  1324800  1094400  806400

[VIDEOCHAT-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig        32000  33000  34000  35000
clr         31000  32000  33000  34000
target      2102   2202   2304   2405

[VIDEOCHAT-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig        42000     45000     50000     51000
clr         40000     43000     48000     50000
target      10100000  12300004  12400001  12500001

[VIDEOCHAT-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device      hotplug_cpu3+hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling     2000
trig        53000
clr         51000
target      1+1+1+1+1


[VIDEOCHAT-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig        49000
clr         47000
target      1

[VIDEOCHAT-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		    6
target		1+1
reverse		1

[VIDEOCHAT-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		46000		48000		50000
clr	     	44000	     	46000	     	48000
target		1		    2		    3

[VIDEOCHAT-MONITOR-HBM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_hbm_disabled
polling		2000
trig		39000
clr		    38000
target		1

[VIDEOCHAT-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight
polling		2000
trig        38000  39000  40000  42000  46000
clr         37000  38000  39000  41000  44000
target      287    507    687    897    1047

