[PHONE-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		2000
trig        35000        38500        49000
clr         34000         37500         47000
target      1324800  1017600  768000

[PHONE-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		2000
trig        35000        38500        49000
clr         34000         37500         47000
target      1555200  1209600  806400

[PHONE-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig        20000
clr         18000
target      2424

[PHONE-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig        42000     45000     50000     51000
clr         40000     43000     49000     50000
target      10100000  10300004  12400001  12500001

[PHONE-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device      hotplug_cpu5+hotplug_cpu6
polling     2000
trig        53000
clr         51000
target      1+1


[PHONE-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		50000
clr		    48000
target		1

[PHONE-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		    6
target		1+1
reverse		1

[PHONE-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		46000		48000		50000
clr		    44000		    46000		    48000
target		1		    2		    3

[PHONE-MONITOR-HBM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_hbm_disabled
polling		2000
trig		39000
clr		    38000
target		1

[PHONE-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight
polling		2000
trig        36500  37500  38500  40500  44500
clr         35500  36500  37500  39500  43500
target      287    507    687    897    1337
