[BAT_SOC]
algo_type	simulated
path		/sys/class/power_supply/battery/capacity
polling		10000

[VIRTUAL-SENSOR]
algo_type	virtual
sensors		battery     quiet_therm     charger_therm     charger_therm1     cpu_therm     pa_therm0
weight		257         422             -107              -378		         350           356
polling		2000
weight_sum	1000
compensation   3119

[GAME-VIRTUAL-SENSOR]
algo_type  virtual
sensors		battery     quiet_therm     charger_therm     charger_therm1     cpu_therm     pa_therm0
weight      26          1030            -13               -543               137           304
polling       2000
weight_sum    1000
compensation  1832

[SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		2000
trig        43000        45000        50000        52500
clr         42000         44000         49000         51000
target      1708800  1497600  1017600  768000

[SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		2000
trig        41000        43000        45000        50000        52500
clr         40000         42000         44000         49000         51000
target      1939200  1843200  1555200  1094400  806400

[MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig        30000  32000  33000  34000  35000  37000  38000  38500  40000  41500  46000
clr         29000  31000  32000  33000  34000  36000  37000  38000  39500  41000  45500
target      0900   1300   1504   1707   1909   2311   2312   2313   2314   2317   2422

[MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig        42000     45000     50000     51000
clr         40000     43000     49000     50000
target      10100000  10300004  12400001  12500001

[MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu5+hotplug_cpu6
polling		2000
trig        54000
clr         53000
target      1+1


[MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig        51000
clr         50000
target      1

[MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		    6
target		1+1
reverse		1

[MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		46000		47000		50000
clr		    41000		    46000		    47000
target		1		    2		    3

[MONITOR-HBM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_hbm_disabled
polling		2000
trig		39000
clr		    38000
target		1

[MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight
polling		2000
trig        36500  37500  38500  40500  44500
clr         35500  36500  37500  39500  43500
target      287    507    687    897    1337

