[CLASS0-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		2000
trig        40000        44000        50000        52500
clr         39000         43000         49000         51000
target      1612800  1497600  1017600  768000

[CLASS0-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		2000
trig        40000        44000        50000        52500
clr         39000         43000         49000         51000
target      1843200  1555200  1094400  806400

[CLASS0-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig        25000  32000  33000  33500  36000  37500
clr         24000  30000  32000  33000  35500  36500
target      1302   1504   1705   1807   1914   2214

[CLASS0-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig        42000     45000     50000     51000
clr         40000     43000     49000     50000
target      10100000  10300004  12400001  12500001

[CLASS0-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		53000
clr		    51000
target		1+1


[CLASS0-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device      boost_limit
polling     2000
trig        50000
clr         48000
target      1

[CLASS0-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		    6
target		1+1
reverse		1

[CLASS0-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		46000		48000		50000
clr		    44000		    46000		    48000
target		1		    2		    3

[CLASS0-MONITOR-HBM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_hbm_disabled
polling		2000
trig		39000
clr		    38000
target		1

[CLASS0-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight
polling		2000
trig        36500  37500  38500  40500  44500
clr         35500  36500  37500  39500  43500
target      287    507    687    897    1337

