[VIRTUAL-SENSOR]
algo_type	virtual
sensors		quiet-therm-usr	
weight		1				
polling		1000

[4K-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		500
trig		41000		47000		54000
clr		39000		45000		52000
target		1516800		1190400		691200

[4K-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		500
trig		42000		48000		55000
clr		41000		47000		54000
target		1766400		1344000		806400

[4K-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		55000
clr		53000
target		5

[4K-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		1000
trig		55000
clr		50000
target		1

[4K-MONITOR-BCL]
algo_type	monitor
sensor		soc
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		5
clr		6
target		1+1
reverse		1

[4K-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		55000
clr		50000
target		2

[4K-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		35000	39000	42000	60000
clr		34000	38000	41000	48000
target          806     1009    1312    1515

[4K-MONITOR-CCC_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7+backlight
polling		1000
trig		55000
clr		53000
target		1+1+1+1+1024
