[VIRTUAL-SENSOR]
algo_type	virtual
sensors		quiet-therm-usr
weight		1
polling		1000

[Phone-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		500
trig		  47500		  50500		  53000		  55000
clr			  47000			  49500			  50500			  53000
target	  1750000  1350000  1000000  800000

[Phone-SS-CPU1]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu1
polling		500
trig		  48500		  51500		  53000		  55000
clr			  47500			  49000			  51500			  53000
target	  1350000  1200000  1000000  800000

[PHONE-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		  25000	60000
clr		    24000	48000
target		1313	1515

[MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		  58000
clr			  54000
target		5

[MONITOR-BCL]
algo_type	monitor
sensor		soc
device		hotplug_cpu4+hotplug_cpu5
polling		1000
trig		  5
clr			  6
target		1+1
reverse		1

[MONITOR-CCC_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu2+hotplug_cpu3
polling		1000
trig		  57000
clr			  54000
target		1+1