[VIRTUAL-SENSOR]
algo_type	virtual
sensors		quiet-therm-usr
weight		1
polling		1000

[Camera-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		500
trig		  50000		  50500		  51500		  52500
clr			  49000			  50000			  50500			  51500
target		1750000 1350000 1000000 400000

[Camera-SS-CPU1]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu1
polling		500
trig		  49500		  51000		  52000		  53000
clr			  48500			  49500			  51000			  52000
target		1500000 1200000 800000  400000

[MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		  54000
clr			  52000
target		2

[MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		  36500 37000 39000 39500 40000 42000 43000 44000 45000
clr		    36000 36500 38000 39000 39500 40000 42000 43000 44000
target    402   503   705   806   907   1008  1109  1310  1511

[MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		  50000
clr			  48000
target		5

[MONITOR-BCL]
algo_type	monitor
sensor		soc
device		hotplug_cpu4+hotplug_cpu5
polling		1000
trig		  5
clr			  6
target		1+1
reverse		1

[MONITOR-CCC_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		  52500
clr			  52000
target		1+1

[MONITOR-CCC_CTRL-1]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu2+hotplug_cpu3
polling		1000
trig		  53000
clr			  52000
target		1+1