[NAV-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		2000
trig		41000		45000		47000		48000		49500		53000
clr		39000		43000		45000		47000		48000		51000
target		1900800		1651200		1516800 	1344000		940800		691200

[NAV-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		2000
trig		41000		45000		47000		48000		49500		53000
clr		39000		43000		45000		47000		48000		51000
target		2035200		1862400		1516800 	1324800		1056000		806400

[NAV-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		32000	38000	39000
clr		30000	37200	38200
target		1308	1412	1515

[NAV-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		44000           45000		48000            50000		51000
clr		41000           44000		46000            48000		50000
target		100002          10100002	10100004         12400001	12500001

[NAV-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling		2000
trig		54000
clr		52000
target		1+1+1+1

[NAV-MONITOR-FLASH]
algo_type	monitor
sensor		flash_therm
device		temp_state
polling		2000
trig		63000
clr		60000
target		10100004

[NAV-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		53000
clr		51000
target		1

[NAV-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		2000
trig		5
clr		6
target		1228800+1+1
reverse		1

[NAV-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		47000		49000		51000
clr		45000		47000		49000
target		0         1        2

[NAV-MONITOR-BACKLIGHT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          backlight-clone
polling         2000
trig            37000    39000    41000    43000     46000
clr             35000    37000    39000    41000     43000
target          695	 2048	  2458	   2867	     3277


[NAV-MONITOR-MODEM-UL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_ul
polling		2000
trig		46000
clr		44000
target		1

[NAV-MONITOR-MODEM-DL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_dl
polling		2000
trig		46000
clr		44000
target		1

[NAV-SS-PARALLEL-TO-SERIAL]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		market_download_limit
polling		2000
trig		40000
clr		38000
target		1
