[BAT_SOC]
algo_type	simulated
path		/sys/class/power_supply/battery/capacity
polling		10000

[VIRTUAL-SENSOR]
algo_type	virtual
sensors		battery		quiet_therm	charger_therm0	wifi_therm	cpu_therm	pa_therm0
weight		28		987		124		-346		79		74
polling		1000
weight_sum	1000
compensation	1771

[GAME-VIRTUAL-SENSOR]
algo_type  virtual
sensors       battery       quiet_therm     charger_therm0     wifi_therm       cpu_therm      pa_therm0
weight        26            1030            -13                -543             137            304
polling       1000
weight_sum    1000
compensation  1832

[INIDA-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		1000
trig		44000		46000		48000		50000		53000
clr		42000		44000		46000		48000		50000
target		1939200		1555200		1324800		1094400		806400

[INIDA-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		35000		36000		37500           39000		41000		42000           46000		60000
clr		33000		35000		36000           37500		39000		41000           42000		46000
target		302		503		904		1109		1309            1412		1414		1515

[INIDA-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		45000		50000		52000
clr		43000		48000		50000
target		10100000	10100004	12400001

[INIDA-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling		2000
trig		55000
clr		50000
target		1+1+1+1


[INIDA-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		55000
clr		50000
target		1

[INIDA-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		6
target		1+1
reverse		1

[INIDA-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		46000		48000		50000
clr		44000		46000		48000
target		0		1		2

[INIDA-MONITOR-HBM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_hbm_disabled
polling		2000
trig		40000
clr		38000
target		1

[INIDA-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight
polling		2000
trig		43000
clr		41000
target		91

