[INIDA-CAMERA-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		1000
trig		42000		44000		46000		48000		50000		53000
clr		40000		42000		44000		46000		48000		50000
target		2208000		1939200		1555200		1324800		1094400		806400

[INIDA-CAMERA-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		35000		37000		39000		41000		43000		45000		48000		60000
clr		33000		35000		37000		39000		41000		43000		45000		48000
target		300		501		602		906		1309		1412		1414		1515

[INIDA-CAMERA-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		45000	    50000	52000
clr		43000	    48000 	50000
target		10100000    10100004	12400001

[INIDA-CAMERA-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling		2000
trig		55000
clr		53000
target		1+1+1+1


[INIDA-CAMERA-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		53000
clr		50000
target		1

[INIDA-CAMERA-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		6
target		1+1
reverse		1

[INIDA-CAMERA-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		46000		48000		50000
clr		44000		46000		48000
target		0		1		2

[INIDA-CAMERA-MONITOR-HBM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_hbm_disabled
polling		2000
trig		40000
clr		38000
target		1

[INIDA-CAMERA-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight
polling		2000
trig		43000
clr		41000
target		91

