[INIDA-MGAME-SS-CPU6]
algo_type	ss
sensor		GAME-VIRTUAL-SENSOR
device		cpu6
polling		1000
trig		20000		53000
clr		19000		50000
target		1843200		844800

[INIDA-MGAME-MONITOR-BAT]
algo_type	monitor
sensor		GAME-VIRTUAL-SENSOR
device		battery
polling		2000
trig            35000    37000    39000    41000    43000    45000    48000    60000
clr             33000    35000    37000    39000    41000    43000    45000    48000
target          300      301      603      906      1309     1412     1414     1515

[INIDA-MGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		GAME-VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		45000		46000		52000
clr		43000		45000		50000
target		10100000	20100000	12400001

[INIDA-MGAME-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		GAME-VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		53000
clr		50000
target		1

[INIDA-MGAME-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		6
target		1+1
reverse		1

[INIDA-MGAME-MONITOR-GPU]
algo_type	monitor
sensor		GAME-VIRTUAL-SENSOR
device		gpu
polling		2000
trig		53000
clr		50000
target		2

[INIDA-MGAME-MONITOR-HBM]
algo_type	monitor
sensor		GAME-VIRTUAL-SENSOR
device		thermal_hbm_disabled
polling		2000
trig		40000
clr		38000
target		1

[INIDA-MGAME-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		GAME-VIRTUAL-SENSOR
device		backlight
polling		2000
trig		43000
clr		41000
target		91

