[VIRTUAL-SENSOR]
algo_type	virtual
sensors		quiet_therm	battery		5G_pa_therm	4G_pa_therm	wifi_therm	msm_therm	chg-skin-therm-usr
weight		-101		182		1471		-949		218		-42		192
polling		2000
weight_sum	1000
compensation	94

[INDIA-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		1000
trig		42000		43000		44000		46000		48000		50000		53000
clr		40000		42000		43000		44000		46000		48000		51000
target		2131200		2073600		1900800		1766400		1555200		1401600		979200

[INDIA-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		35000	37400	38800	39300	40000	42000	44000	46000	60000
clr		34000	35000	37400	38800	39300	40000	42000	44000	58000
target	     	600	803	905	1007	1108	1208	1309	1410	1515

[ABT-SENSOR]
algo_type	ambient
sensors		conn_therm	quiet_therm
coefficient_a	1125		1263
coefficient_b	-1115		-1163
compensation	-9000		-11000
polling		10000
weight_sum	10

[INDIA-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		45000		53000
clr		44000		51000
target		10100000	12400001

[INDIA-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		1000
trig		55000
clr		52000
target		1

[INDIA-MONITOR-BCL]
algo_type	monitor
sensor		bat_soc
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		5
clr		6
target		1+1
reverse		1

[INDIA-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		48000		50000		53000
clr		46000		48000		50000
target		0	1	2

[INDIA-MONITOR-CCC_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		51000
clr		50000
target		1+0


[INDIA-MODEM-UL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_ul
polling		1000
trig		47000
clr		45000
target		1

[INDIA-MODEM-DL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_dl
polling		1000
trig		47000
clr		45000
target		1
