[TGAME-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		1000
trig		51000		52000
clr		50000		51000
target		2131200		1900800

[TGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		53000
clr		51000
target		12400001

[TGAME-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		1000
trig		55000
clr		50000
target		1

[TGAME-MONITOR-BCL]
algo_type	monitor
sensor		bat_soc
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		5
clr		6
target		1+1
reverse		1

[TGAME-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		53000
clr		48000
target		2

[TGAME-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		38000	40800	41800	42300	43000	45000	47000	49000	63000
clr		37000	38000	40800	41800	42300	43000	45000	46000	61000
target	     	500	603	805	907	1008	1108	1208	1409	1515

[TGAME-MODEM-UL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_ul
polling		1000
trig		47000
clr		45000
target		1

[TGAME-MODEM-DL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_dl
polling		1000
trig		47000
clr		45000
target		1

