[PHONE-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		2000
trig        34000        37500        48000
clr         33000         36500         46000
target      1375000  1050000  774000

[PHONE-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		2000
trig        34000        37500        48000
clr         33000         36500         46000
target      1532000  1295000  850000

[PHONE-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig        20000
clr         18000
target      3535

[PHONE-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig        42000     45000     50000     51000
clr         40000     43000     49000     50000
target      10100000  10300004  12400001  12500001

[PHONE-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device      hotplug_cpu5+hotplug_cpu6
polling     2000
trig        52000
clr         50000
target      1+1


[PHONE-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		49000
clr		    47000
target		1

[PHONE-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		    6
target		1+1
reverse		1

[PHONE-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		45000		47000		49000
clr		    43000		    45000		    47000
target		1		    2		    3

[PHONE-MONITOR-HBM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_hbm_disabled
polling		2000
trig		39000
clr		    38000
target		1

[PHONE-MONITOR-MTK-CL-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		mtk-cl-backlight
polling		2000
trig        39000  41000  43000  46000
clr         38000  40000  42000  45000
target      80    60    40    20
