[NOLIMITS-SS-CPU4]
algo_type	ss
sensor	VIRTUAL-SENSOR0
device	cpu4
polling	1000
trig	55000
clr	54000
target	633600

[NOLIMITS-SS-CPU7]
algo_type	ss
sensor	VIRTUAL-SENSOR0
device	cpu7
polling	1000
trig	55000
clr	54000
target	787200

[NOLIMITS-MONTIOR-SENSOR0]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	VIRTUAL-SENSOR0
polling	10000
trig	25000	33000	38000	43000
clr	24500	31500	37500	42500
target	10000	5000	2000	1000

[NOLIMITS-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	battery
polling	2000
trig	20000	33000	40000
clr	18000	31000	38000
target	808	1313	1515

[NOLIMITS-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	temp_state
polling	2000
trig	50000	51000	53000
clr	48000	50000	51000
target	12310004	12510001	12520001

[NOLIMITS-MONITOR-FLASH]
algo_type	monitor
sensor	flash_therm
device	temp_state
polling	2000
trig	65000
clr	62000
target	10100004

[NOLIMITS-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	gpu
polling	2000
trig	55000
clr	54000
target	1

[NOLIMITS-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	backlight-clone
polling	2000
trig	37000	39000	41000	43000	46000
clr	35000	37000	39000	41000	43000
target	140	100	80	50	32

[NOLIMITS-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR0
device	market_download_limit
polling	2000
trig	40000
clr	37000
target	1

