[INDIA-HP-GAME-SS-CPU0]	
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu0
polling	2000
trig	48000	49000	50000
clr	47000	48000	49000
target	1632000	1478400	806400

[INDIA-HP-GAME-SS-CPU6]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu6
polling	2000
trig	48000	49000	50000
clr	47000	48000	49000
target	1900800	1497600	960000

[INDIA-MGAME-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	battery
polling	2000
trig	25000	28000
clr	23000	26000
target	1414	1515

[INDIA-HP-GAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	temp_state
polling	2000
trig	41000	43000	46000	47000
clr	40000	41000	45000	46000
target	110100004	112110004	112320004	112520004

[INDIA-HP-GAME-MONITOR-CCC]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	hotplug_cpu0+hotplug_cpu1+hotplug_cpu6
polling	2000
trig	52000
clr	50000
target	1+1+1

[INDIA-HP-GAME-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	boost_limit
polling	2000
trig	52000
clr	50000
target	1

[INDIA-HP-GAME-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	gpu
polling	2000
trig	51000
clr	49000
target	2

[INDIA-HP-GAME-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	thermal_max_brightness
polling	2000
trig	51000
clr	49000
target	160

[INDIA-HP-GAME-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	market_download_limit
polling	2000
trig	40000
clr	37000
target	1

[INDIA-HP-GAME-MONITOR-5GTO4G]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	modem_limit
polling	2000
trig	47000
clr	43000
target	1

[INDIA-HP-GAME-MONITOR-FLASH]
algo_type	monitor
sensor	flash_therm
device	temp_state
polling	2000
trig	56000
clr	54000
target	110100004
