[INDIA-NOLIMITS-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling	2000
trig		55000
clr		53000
target		499200

[INDIA-NOLIMITS-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling	2000
trig		55000
clr		53000
target		691200

[INDIA-NOLIMITS-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling	2000
trig	25000	28000
clr	23000	26000
target	1414	1515

[INDIA-NOLIMITS-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling	2000
trig		51000	53000
clr		50000	51000
target		112510004	112520004

[INDIA-NOLIMITS-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling	2000
trig		53000
clr		50000
target		1

[INDIA-NOLIMITS-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_max_brightness
polling	2000
trig		51000
clr		49000
target		160

[INDIA-NOLIMITS-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		market_download_limit
polling	2000
trig		40000
clr		37000
target		1

[INDIA-NOLIMITS-MONITOR-FLASH]
algo_type	monitor
sensor		flash_therm
device		temp_state
polling	2000
trig		56000
clr		54000
target		110100004
