[INDIA-CGAME-SS-CPU0]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu0
polling	2000
trig	48000	49000	50000
clr	47000	48000	49000
target	1804800	1286400	672000

[INDIA-CGAME-SS-CPU6]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu6
polling	2000
trig	48000	49000	50000
clr	47000	48000	49000
target	2054400	1497600	960000

[INDIA-CGAME-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	battery
polling	2000
trig	32000	35000	36000	37000	39000	41000
clr	30000	34000	35000	36000	38000	39000
target	600	701	803	909	1010	1414

[INDIA-CGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	temp_state
polling	2000
trig	15000	48000	51000	53000
clr	13000	46000	50000	51000
target	110100000	110300004	112310004	112520004

[INDIA-CGAME-MONITOR-CCC]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	hotplug_cpu0+hotplug_cpu1+hotplug_cpu6
polling	2000
trig	55000
clr	53000
target	1+1+1

[INDIA-CGAME-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	boost_limit
polling	2000
trig	53000
clr	51000
target	1

[INDIA-CGAME-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	gpu
polling	2000
trig	51000
clr	49000
target	2

[INDIA-CGAME-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	thermal_max_brightness
polling	2000
trig	51000
clr	49000
target	160

[INDIA-CGAME-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	market_download_limit
polling	2000
trig	40000
clr	37000
target	1

[INDIA-CGAME-MONITOR-5GTO4G]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	modem_limit
polling	2000
trig	47000
clr	43000
target	1

[INDIA-CGAME-MONITOR-FLASH]
algo_type	monitor
sensor	flash_therm
device	temp_state
polling	2000
trig	56000
clr	54000
target	110100004
