[GL-HP-MGAME-SS-CPU6]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu6
polling	2000
trig	51000
clr	49000
target	650000

[GL-HP-MGAME-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	battery
polling	2000
trig	35000	37000	38400	39000	39800	40900	41100	41800	43000	43800	44200	44700	47000
clr	34000	35000	37000	38400	39000	39800	41000	41100	41800	43000	43800	44200	45000
target	100	100	200	203	409	909	1010	1111	1213	1313	1314	1515	1515

[GL-HP-MGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	temp_state
polling	2000
trig	44000	46000	47000
clr	43000	45000	46000
target	12110004	12320004	12520001

[GL-HP-MGAME-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	boost_limit
polling	2000
trig	51000
clr	49000
target	1

[GL-HP-MGAME-MONITOR-BCL]
algo_type	monitor
sensor	BAT_SOC
device	hotplug_cpu6+hotplug_cpu7
polling	2000
trig	5
clr	6
target	1+1
reverse	1

[GL-HP-MGAME-MONITOR-CPU]
algo_type	monitor
sensor	CPU_SOC
device	hotplug_cpu6+hotplug_cpu7
polling	2000
trig	90000
clr	85000
target	1+1

[GL-HP-MGAME-MONITOR-BACKLIGHT_CTRL]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	backlight-clone
polling	2000
trig	37000	39000	41000	43000	46000
clr	35000	37000	39000	41000	43000
target	150	100	80	50	32

[GL-HP-MGAME-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	gpu
polling	2000
trig	50000
clr	48000
target	20
target	1

[GL-HP-MGAME-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	market_download_limit
polling	10000
trig	40000
clr	37000
target	1

[GL-HP-MGAME-MONITOR-PA_POWER]
algo_type	monitor
sensor	mtktsbtsmdpa
device	mtk_cl_tx_pwr00+mtk_cl_tx_pwr01+mtk_cl_tx_pwr02
polling	2000
trig	80000	84000	88000
clr	78000	80000	84000
target	1+0+0	0+1+0	0+0+1

[GL-HP-MGAME-MONITOR-NRPA_POWER]
algo_type	monitor
sensor	mtktsbtsmdpa
device	mtk_cl_tx_pwr00_nr+mtk_cl_tx_pwr01_nr+mtk_cl_tx_pwr02_nr
polling	2000
trig	80000	84000	88000
clr	78000	80000	84000
target	1+0+0	0+1+0	0+0+1

[GL-HP-MGAME-MONITOR-FLASH]
algo_type	monitor
sensor	flash_therm
device	temp_state
polling	2000
trig	56000
clr	53000
target	10100004

[GL-HP-MGAME-MONITOR-MODEM]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	mtk-cl-scg-off
polling	2000
trig	49000
clr	47000
target	1

[GL-HP-MGAME-MONITOR-MODEM-5GTO4G]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	modem_limit
polling	2000
trig	45000
clr	43000
target	1