[VIRTUAL-SENSOR]
algo_type	virtual
sensors		mtktsAP
weight		1
polling		1000

[SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		1000
trig		  46000		  48000		  50000
clr			  45000			  46000			  48000
target		1500000  1175000  975000

[SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		1000
trig		  46500		  48500		  50500
clr			  46000			  47000			  49500
target		1530000  1308000  1085000

[MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		  26000	28000	29000	30000	31000	32000	33000 34000
clr		    25000	27000	28000	29000	30000	31000	32000 33000
target    101		302		403		807		1009	1611	1712  1812

[MONITOR-CPU_HOTPLUG]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu5+hotplug_cpu6
polling		1000
trig		  55000
clr			  54000
target		1+1

[MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		  55000
clr		    52000
target		5

[MONITOR-CCC_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		  61000
clr			  58000
target		1+1

[MONITOR-MTK-CL-BACKLIGHT]
algo_type monitor
sensor    VIRTUAL-SENSOR
device    mtk-cl-backlight
polling   1000
trig      47500  48500
clr       46000  47500
target    1700   1500