[VIRTUAL-SENSOR]
algo_type	virtual
sensors		mtktsAP
weight		1
polling		1000

[SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		500
trig		  49500		  51500
clr			  48500			  49500
target		1375000  1075000

[SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		500
trig		  49000		  52000
clr			  48000			  49000
target		1169000  835000

[MONITOR-BAT-1]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		  38000   39500   40000   40500
clr		    37000   39000   39500   40000
target    1004    1205	  1309    1411

[MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		  58000
clr		    54000
target		5

[MONITOR-CCC_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		  61000
clr			  58000
target		1+1

[MONITOR-MTK-CL-BACKLIGHT]
algo_type monitor
sensor    VIRTUAL-SENSOR
device    mtk-cl-backlight
polling   1000
trig      48000  49000
clr       47000  48000
target    1700   1500