[PHONE-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		1000
trig		33000		51000
clr		31000		48000
target		1209600		710400

[PHONE-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		1000
trig		33000		51000
clr		31000		48000
target		1420800		844800

[PHONE-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		22000	42000
clr		20000	40000
target		1414	1515

[PHONE-MONITOR-WIRELESS]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		wireless_charge
polling		2000
trig		22000     37000
clr		20000     35000
target		1313      1414

[PHONE-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		48000		53000
clr		46000		51000
target		10100000	12400001

[PHONE-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling		2000
trig		54000
clr		52000
target		1+1+1+1

[PHONE-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		54000
clr		52000
target		1

[PHONE-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		2000
trig		5
clr		6
target		1209600+1+1
reverse		1

[PHONE-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight-clone
polling		2000
trig		37000	39000	41000	43000	46000
clr		35000	37000	39000	41000	43000
target		2048	4096	4914	6143	6878

[PHONE-MODEM-UL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_ul
polling		2000
trig		46000
clr		43000
target		1

[PHONE-MODEM-DL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_dl
polling		2000
trig		46000
clr		43000
target		1
