[CGAME-SS-CPU0]
algo_type	ss
sensor	VIRTUAL-SENSOR-FORMULA
device	cpu0
polling	1000
trig	29000	50000
clr	27000	48000
target	1400000	1000000

[CGAME-SS-CPU4]
algo_type	ss
sensor	VIRTUAL-SENSOR-FORMULA
device	cpu4
polling	1000
trig	29000	50000
clr	27000	48000
target	2500000	1000000

[CGAME-SS-CPU7]
algo_type	ss
sensor	VIRTUAL-SENSOR-FORMULA
device	cpu7
polling	1000
trig	29000	50000
clr	27000	48000
target	2800000	1000000

[CGAME-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	battery
polling	2000
trig	30000	33000	35000	37000	40000	42000	44000	45500
clr	29000	32000	34000	36500	38700	41500	43500	45200
target	202	202	404	707	909	1010	1313	1515

[CGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	temp_state
polling	2000
trig	43000	50000	51000	53000
clr	42000	48000	50000	51000
target	110100000	110300001	112310001	112520001

[CGAME-MONITOR-FLASH]
algo_type	monitor
sensor	flash_therm
device	temp_state
polling	2000
trig	65000
clr	60000
target	110100004

[CGAME-MONITOR-CCC]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	cpu0+hotplug_cpu4+hotplug_cpu7
polling	2000
trig	49000	54000
clr	47000	52000
target	1200000+1+0	1200000+1+1

[CGAME-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	boost_limit
polling	2000
trig	54000
clr	52000
target	1

[CGAME-MONITOR-BCL]
algo_type	monitor
sensor	BAT_SOC
device	cpu0+cpu4+cpu7+gpu
polling	2000
trig	5
clr	6
target	2000000+1200000+1300000+9
reverse	1

[CGAME-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	gpu
polling	2000
trig	19000	29000	51000
clr	17000	19000	49000
target	31	32	35

[CGAME-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	thermal_max_brightness
polling	2000
trig	51000
clr	49000
target	160

[CGAME-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	market_download_limit
polling	2000
trig	40000
clr	37000
target	1

[CGAME-MONITOR-TORCH-LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	torch_level
polling	2000
trig	48000	50000
clr	45000	48000
target	1	2

[CGAME-MONITOR-HDR]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	super_hdr
polling	2000
trig	40000
clr	38000
target	1

[CGAME-MONITOR-BCL-AWARE]
algo_type       monitor
sensor  TEMP_AWARE
device	cpu0+cpu4+hotplug_cpu7+gpu+boost_limit+temp_state
polling	2000
trig	1   2
clr	2   3
target  2000000+1200000+1+16+1+110100000  2000000+1200000+1+9+1+110100000
reverse	1
