[NOLIMITS-SS-CPU0]
algo_type	ss
sensor	VIRTUAL-SENSOR-FORMULA
device	cpu0
polling	1000
trig	52000	55000
clr	50000	54000
target	1800000	500000

[NOLIMITS-SS-CPU4]
algo_type	ss
sensor	VIRTUAL-SENSOR-FORMULA
device	cpu4
polling	1000
trig	52000	55000
clr	50000	54000
target	2900000	622000

[NOLIMITS-SS-CPU7]
algo_type	ss
sensor	VIRTUAL-SENSOR-FORMULA
device	cpu7
polling	1000
trig	52000	55000
clr	50000	54000
target	2800000	798000

[NOLIMITS-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	battery
polling	2000
trig	33000	35000	38000	40000	41500	44500	45000
clr	32000	34000	37700	38700	41200	43700	44700
target	404	505	707	909	1010	1414	1515

[NOLIMITS-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	temp_state
polling	2000
trig	51000	53000
clr	50000	52000
target	110300001	112520001

[NOLIMITS-MONITOR-FLASH]
algo_type	monitor
sensor	flash_therm
device	temp_state
polling	2000
trig	65000
clr	60000
target	110100004

[NOLIMITS-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	boost_limit
polling	2000
trig	55000
clr	53000
target	1

[NOLIMITS-MONITOR-BCL]
algo_type	monitor
sensor	BAT_SOC
device	cpu0+cpu4+cpu7+gpu
polling	2000
trig	5
clr	6
target	1400000+1800000+2200000+9
reverse	1

[NOLIMITS-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	gpu
polling	2000
trig	47000	49000	52000
clr	45000	47000	51000
target	15	20	40

[NOLIMITS-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	thermal_max_brightness
polling	2000
trig	51000
clr	49000
target	160

[NOLIMITS-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	market_download_limit
polling	2000
trig	40000
clr	37000
target	1

[NOLIMITS-MONITOR-TORCH-LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR-FORMULA
device	torch_level
polling	2000
trig	48000	50000
clr	45000	48000
target	1	2

[NOLIMITS-MONITOR-BCL-AWARE]
algo_type       monitor
sensor  TEMP_AWARE
device	cpu0+cpu4+hotplug_cpu7+gpu+boost_limit+temp_state
polling	2000
trig	1   2
clr	2   3
target  1200000+1200000+1+16+1+110100000  1200000+1200000+1+9+1+110100000
reverse	1
