[INDIA-PHONE-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		1000
trig		33000		38000		48000
clr		31000		36000		46000
target		1228800		940800		691200

[INDIA-PHONE-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		1000
trig		33000		38000		48000
clr		31000		36000		46000
target		1324800		1056000		806400

[INDIA-PHONE-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		15000
clr		14000
target		1515

[INDIA-PHONE-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		48000		51000		53000		54000
clr		46000		49000		52000		53000
target		10100004	12100004	12400001	12520001

[INDIA-PHONE-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu2+hotplug_cpu3+hotplug_cpu7
polling		2000
trig		55000
clr		53000
target		1+1+1

[INDIA-PHONE-MONITOR-FLASH]
algo_type	monitor
sensor		flash_therm
device		temp_state
polling		2000
trig		65000
clr		60000
target		10100004

[INDIA-PHONE-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		55000
clr		53000
target		1

[INDIA-PHONE-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		6
target		1+1
reverse		1

[INDIA-PHONE-MONITOR-GPU]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          gpu
polling         2000
trig            49000            51000            54000
clr             47000             49000             51000
target          0	1	2

[INDIA-PHONE-MONITOR-BACKLIGHT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          backlight-clone
polling         2000
trig            37000    39000    41000    43000     46000
clr             35000    37000    39000    41000     43000
target          910	 2048	  2276	   2958	     3368

[INDIA-PHONE-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		market_download_limit
polling		10000
trig		40000
clr		37000
target		1

[INDIA-PHONE-MONITOR-WIFI-LIMIT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          wifi_limit
polling         2000
trig            35000
clr             33000
target          1
