[VIRTUAL-SENSOR]
algo_type        virtual
sensors          mtktsAP
weight           1
polling          1000

[WEIBO-SS-CPU0]
algo_type        ss
sensor           VIRTUAL-SENSOR
device           cpu0
polling          1000
trig             39000             41000             43000             44000             46000             49000             52000             54000
clr              38000              40000              42000              43000              45000              46000              50000              52000
target           2000000  1866000  1800000  1733000  1666000  1075000  774000  500000

[WEIBO-SS-CPU6]
algo_type        ss
sensor           VIRTUAL-SENSOR
device           cpu6
polling          1000
trig             39000             41000             43000             44000             46000             49000             52000             54000
clr              38000              40000              42000              43000              45000              46000              50000              52000
target           2050000  1923000  1860000  1796000  1733000  1085000  835000  774000

[WEIBO-MONITOR-GPU]
algo_type        monitor
sensor           VIRTUAL-SENSOR
device           gpu
polling          1000
trig             45000   50000   55000
clr              40000   45000   50000
target           10      15      20

[WEIBO-MONITOR-BOOST_LIMIT]
algo_type        monitor
sensor           VIRTUAL-SENSOR
device           boost_limit
polling          2000
trig             52000
clr              49000
target           1

[WEIBO-MONITOR-MTK-CL-BACKLIGHT]
algo_type        monitor
sensor           mtktsAP
device           mtk-cl-backlight
polling          2000
trig             40000  42000  44000  46000
clr              38000  40000  42000  44000
target           82     72     62     52

[WEIBO-MONITOR-BAT]
algo_type        monitor
sensor           mtktsAP
device           battery
polling          2000
trig             30000  38000  39000  40000  47000
clr              29000  37000  38000  39000  46000
target           1302   1504   1705   1807   2414

[WEIBO-MONITOR-FLASH-TEMP_STATE]
algo_type        monitor
sensor           flash_therm
device           temp_state
polling          2000
trig             54000
clr              52000
target           10100004

[WEIBO-MONITOR-BATTERY-TEMP_STATE]
algo_type        monitor
sensor           battery
device           temp_state
polling          2000
trig             51000
clr              49000
target           15300001

[WEIBO-MONITOR-HOTPLUG_CTRL]
algo_type        monitor
sensor           VIRTUAL-SENSOR
device           hotplug_cpu5+hotplug_cpu6
polling          2000
trig             60000
clr              55000
target           1+1

[WEIBO-MONITOR-BCL]
algo_type        monitor
sensor           bat_soc
device           hotplug_cpu6+hotplug_cpu7
polling          2000
trig             5
clr              6
target           1+1
reverse          1
