[VIRTUAL-SENSOR]
algo_type	virtual
sensors		quiet_therm	xo_therm	conn_therm
weight		4		2		1
polling		1000

[INDIA-TGAME-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		500
trig		55000
clr		54000
target		109400

[INDIA-TGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		62000
clr		50000
target		5

[INDIA-TGAME-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		1000
trig		55000
clr		50000
target		1

[INDIA-TGAME-MONITOR-BCL]
algo_type	monitor
sensor		bat_soc
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		5
clr		6
target		1+1
reverse		1

[INDIA-TGAME-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		55000
clr		50000
target		2

[INDIA-TGAME-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		33000	35000	38000	40000	42000	60000
clr		32000	34000	37000	39000	41000	48000
target		600	900     1005	1210	1411    1515
