[BAT_SOC]
algo_type	simulated
path		/sys/class/power_supply/battery/capacity
polling		10000

[VIRTUAL-SENSOR]
algo_type	virtual
sensors		quiet_therm	battery
weight		5		3
polling		1000

[TGAME-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		500
trig		55000
clr		53000
target		1497600

[TGAME-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		500
trig		55000
clr		53000
target		1401600

[TGAME-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		500
trig		55000
clr		53000
target		1305600

[TGAME-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		35000	36000	37000	38000	39000	40000	41000	41500	42000	42500	43000	50000
clr		31000	35000	36000	37000	38000	39000	40000	41000	41500	42000	42500	43000
target		800	900	1000	1002	1205	1206	1308	1309	1410	1413	1414	1515

[TGAME-MONITOR-WIRELESS]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		wireless_charge
polling		1000
trig		40500	41900	42500	43000	43500
clr		38000	40500	41900	42500	43000
target		1	4	6	8	13

[TGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		53000
clr		48000
target		4

[TGAME-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		1000
trig		55000
clr		52000
target		1

[TGAME-MODEM1-PA]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          5g_modem_pa0
polling         1000
trig            47000    49000
clr             45000    47000
target          1        3

[TGAME-MODEM1-PROC]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          5g_modem_tsens
polling         1000
trig            47000    49000
clr             45000    47000
target          1        3

[TGAME-MONITOR-CPU1]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          hotplug_cpu1
polling         1000
trig            55000
clr             51000
target          1


