[TGAME-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR-GAME
device		cpu4
polling		1000
trig		54000
clr		52000
target		710400

[TGAME-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR-GAME
device		cpu7
polling		1000
trig		54000
clr		52000
target		844800

[TGAME-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR-GAME
device		gpu
polling		2000
trig		54000
clr		52000
target		9

[TGAME-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR-GAME
device		battery
polling		2000
trig		36000	38000	39000	41000	43000	45000	48000	60000
clr		35000	36000	38000	39000	41000	43000	45000	48000
target		303	707	808	909	1111	1313	1414	1515

[TGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR-GAME
device		temp_state
polling		2000
trig		52000
clr		50000
target		12400001

[TGAME-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		2000
trig		5
clr		6
target		1209600+1+1
reverse		1

[TGAME-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR-GAME
device		backlight-clone
polling		2000
trig		37000	39000	41000	43000	46000	48000
clr		35000	37000	39000	41000	43000	46000
target		2048	4096	4914	6143	7044	7290

[TGAME-MODEM-UL]
algo_type	monitor
sensor		VIRTUAL-SENSOR-GAME
device		modem_ul
polling		2000
trig		48000
clr		43000
target		1

[TGAME-MODEM-DL]
algo_type	monitor
sensor		VIRTUAL-SENSOR-GAME
device		modem_dl
polling		2000
trig		48000
clr		43000
target		1

