[MGAME-UNFOLD-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR-UNFOLD-GAME
device		cpu4
polling		1000
trig		21000		52000
clr		20000		50000
target		1881600		710400

[MGAME-UNFOLD-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR-UNFOLD-GAME
device		cpu7
polling		1000
trig		21000		52000
clr		20000		50000
target		1785600		844800

[MGAME-UNFOLD-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR-UNFOLD-GAME
device		battery
polling		2000
trig		36000	38000	39000	41000	43000	45000	48000	60000
clr		35000	36000	38000	39000	41000	43000	45000	48000
target		202	505	606	707	808	1212	1414	1515

[MGAME-UNFOLD-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR-UNFOLD-GAME
device		temp_state
polling		2000
trig		45000		52000
clr		43000		50000
target		10100000	12400001

[MGAME-UNFOLD-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		2000
trig		5
clr		6
target		1209600+1+1
reverse		1

[MGAME-UNFOLD-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR-UNFOLD-GAME
device		gpu
polling		2000
trig		52000
clr		50000
target		9

[MGAME-UNFOLD-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR-UNFOLD-GAME
device		backlight-clone
polling		2000
trig		37000	39000	41000	43000	46000	48000
clr		35000	37000	39000	41000	43000	46000
target		2048	4096	4914	6143	7044	7290

[MGAME-UNFOLD-MODEM-UL]
algo_type	monitor
sensor		VIRTUAL-SENSOR-UNFOLD-GAME
device		modem_ul
polling		2000
trig		48000
clr		43000
target		1

[MGAME-UNFOLD-MODEM-DL]
algo_type	monitor
sensor		VIRTUAL-SENSOR-UNFOLD-GAME
device		modem_dl
polling		2000
trig		48000
clr		43000
target		1


