[BAT_SOC]
algo_type	simulated
path		/sys/class/power_supply/battery/capacity
polling		10000

[VIRTUAL-SENSOR]
algo_type	virtual
sensors		cam_therm1        battery        conn_therm        quiet_therm        wireless_therm        xo_therm
weight		1149              147            -193              408                -228                  -385
polling		1000
weight_sum	1000
compensation	3222

[5G-SENSOR]
algo_type	virtual
sensors		battery        cam_therm1        quiet_therm        xo_therm
weight		659            -277              255                228
polling		1000
weight_sum	1000
compensation	4056

[ABT-SENSOR]
algo_type	ambient
sensors		conn_therm	quiet_therm
coefficient_a	781		931
coefficient_b	-771		-921
compensation	-13000		-15000
polling		10000
weight_sum	10

[SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		1000
trig		19000		43000		45000		47000		49000		51000		55000
clr		18000		41000		43000		45000		47000		49000		53000
target		2246400		1862400		1766400		1574400 	1478400		1286400		710400

[SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		1000
trig		19000		43000		45000		47000		49000		51000		55000
clr		18000		41000		43000		45000		47000		49000		53000
target		2745600		1862400		1747200		1516800		1401600		1305600		844800

[MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		39000	41000	43000	44000	45000	46000	47000	48000	61000
clr		36000	39000	41000	43000	44000	45000	46000	47000	49000
target		804	1006	1208	1208	1209	1410	1512	1514	1515

[MONITOR-WIRELESS]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		wireless_charge
polling		2000
trig		37000	38600	39400	40200	41000	42000	43000
clr		35000	37000	38600	39400	40200	41000	42000
target		400	601	603	805	807	1009	1313

[MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		45000		53000
clr		44000		51000
target		10100000	12400001

[MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling		2000
trig		55000
clr		53000
target		1+1+1+1

[MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		55000
clr		52000
target		1

[MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		2000
trig		5
clr		6
target		1286400+1+1
reverse		1

[MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		54000
clr		51000
target		2

[MONITOR-HBM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		thermal_hbm_disabled
polling		2000
trig		40000
clr		38000
target		1

[MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight
polling		2000
trig		42000
clr		39000
target		287

[MODEM-UL]
algo_type       monitor
sensor          5G-SENSOR
device          modem_ul
polling         2000
trig            48000
clr             43000
target          1

[MODEM-DL]
algo_type       monitor
sensor          5G-SENSOR
device          modem_dl
polling         2000
trig            48000
clr             43000
target          1
