[VIRTUAL-SENSOR]
algo_type	virtual
sensors		quiet-therm
weight		1
polling		1000

[SS-CPU0]
algo_type	ss
sensor		sdm-therm
device		cpu0
polling		2000
trig		49000
clr			47000
target		1516800

[SS-CPU0-1]
algo_type	ss
sensor		sdm-therm
device		cpu0
polling		2000
trig		51000
clr			49000
target		1209600

[SS-CPU0-2]
algo_type	ss
sensor		sdm-therm
device		cpu0
polling		2000
trig		52000
clr			50000
target		748800

[SS-CPU6]
algo_type	ss
sensor		sdm-therm
device		cpu6
polling		2000
trig		48000
clr			46000
target		1708800

[SS-CPU6-1]
algo_type	ss
sensor		sdm-therm
device		cpu6
polling		2000
trig		50000
clr			48000
target		1209600

[SS-CPU6-2]
algo_type	ss
sensor		sdm-therm
device		cpu6
polling		2000
trig		51000
clr			49000
target		768000

[MONITOR-CPU5]
algo_type	monitor
sensor		sdm-therm
device		hotplug_cpu5
polling		1000
trig		47000
clr			45000
target		1

[MONITOR-CPU3]
algo_type	monitor
sensor		sdm-therm
device		hotplug_cpu3
polling		1000
trig		49000
clr			47000
target		1

[MONITOR-CPU7]
algo_type	monitor
sensor		sdm-therm
device		hotplug_cpu7
polling		1000
trig		51000
clr			49000
target		1

[MONITOR-CPU2]
algo_type	monitor
sensor		sdm-therm
device		hotplug_cpu2
polling		1000
trig		51000
clr			49000
target		1

[MONITOR-BAT]
algo_type	monitor
sensor		quiet-therm
device		battery
polling		1000
trig		26000	28000	29000	30000	31000	32000	33000   34000
clr		    25000	27000	28000	29000	30000	31000	32000   33000
target      101		302		403		807		1009	1311	1412    1512

[MONITOR-CPU_HOTPLUG]
algo_type	monitor
sensor		quiet-therm
device		hotplug_cpu0+hotplug_cpu1+hotplug_cpu4
polling		1000
trig		55000
clr			52000
target		1+1+1

[MONITOR-TEMP_STATE]
algo_type	monitor
sensor		quiet-therm
device		temp_state
polling		1000
trig		54000
clr		    51000
target		1

[MONITOR-LCD]
algo_type	monitor
sensor		backlight_therm
device		backlight
polling		1000
trig		41000  43000
clr		    40000  42000
target		819    1230

[MONITOR-CCC_CTRL]
algo_type	monitor
sensor		quiet-therm
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		61000
clr			58000
target		1+1