[MGAME-SS-CPU0]
algo_type	ss
sensor		sdm-therm
device		cpu0
polling		2000
trig		20000		51000
clr		    18000		    48000
target		1708800  576000

[MGAME-SS-CPU6]
algo_type	ss
sensor		sdm-therm
device		cpu6
polling		2000
trig		20000		50000
clr		    18000		    47000
target		1900800  768000

[MGAME-MONITOR-GPU]
algo_type	monitor
sensor		sdm-therm
device		gpu
polling		1000
trig		51000
clr		    49000
target		3

[MGAME-MONITOR-CPU3]
algo_type	monitor
sensor		sdm-therm
device		hotplug_cpu3
polling		1000
trig		51000
clr			49000
target		1

[MGAME-MONITOR-CPU2]
algo_type	monitor
sensor		sdm-therm
device		hotplug_cpu2
polling		1000
trig		52000
clr			50000
target		1

[MGAME-MONITOR-CPU5]
algo_type	monitor
sensor		sdm-therm
device		hotplug_cpu5
polling		1000
trig		52500
clr			50000
target		1

[MGAME-MONITOR-CPU4]
algo_type	monitor
sensor		sdm-therm
device		hotplug_cpu4
polling		1000
trig		51500
clr			49000
target		1

[MONITOR-BAT]
algo_type	monitor
sensor		quiet-therm
device		battery
polling		1000
trig		26000	30000
clr		    25000	29000
target		1412	1512

[MONITOR-TEMP_STATE]
algo_type	monitor
sensor		quiet-therm
device		temp_state
polling		1000
trig		54000
clr		    51000
target		1

[MONITOR-CCC_CTRL]
algo_type	monitor
sensor		quiet-therm
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		61000
clr		    58000
target		1+1