[VIRTUAL-SENSOR]
algo_type       virtual
sensors         quiet-therm-usr
weight          1
polling         1000

[MGAME-SS-CPU0]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0
polling         500
trig            47000            49000            51000
clr             45000             47000             49000
target          1574400  1324800  1190400

[MGAME-SS-CPU1]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu1
polling         500
trig            47000            49000            51000
clr             45000             47000             49000
target          1574400  1324800  1190400

[MGAME-SS-CPU2]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu2
polling         500
trig            47000            49000            51000
clr             45000             47000             49000
target          1574400  1324800  1190400

[MGAME-SS-CPU3]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu3
polling         500
trig            47000            49000            51000
clr             45000             47000             49000
target          1574400  1324800  1190400

[MGAME-SS-CPU4]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu4
polling         500
trig            47000            49000            51000
clr             45000             47000             49000
target          1574400  1324800  1190400

[MGAME-SS-CPU5]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu5
polling         500
trig            47000            49000            51000
clr             45000             47000             49000
target          1574400  1324800  1190400

[MGAME-SS-CPU6]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu6
polling         500
trig            50000            52000            54000
clr             48000             50000             52000
target          1804800  1651200  1401600

[MGAME-SS-CPU7]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu7
polling         500
trig            50000            52000            54000
clr             48000             50000             52000
target          1804800  1651200  1401600

[MGAME-MONITOR-BAT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          battery
polling         1000
trig            38000  39000  40000  41000  42000  43000  44000  45000  46000  47000  48000  49000
clr             37000  38000  39000  40000  41000  42000  43000  44000  45000  46000  47000  48000
target          0113   0214   0315   0416   0517   0618   0719   0820   0921   1022   1123   1224

[MGAME-MONITOR-TEMP_STATE]
algo_type       monitor
sensor          xo-therm-usr
device          temp_state
polling         1000
trig            60000
clr             58000
target          5

[MGAME-MONITOR-CL-BACKLIGHT]
algo_type       monitor
sensor          backlight_therm
device          backlight_therm
polling         1000
trig            40000    42000    44000    46000    48000
clr             38000    40000    42000    44000    46000
target          1024      1638     2048    2866     3276

[MGAME-MONITOR-BOOST_LIMIT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          boost_limit
polling         1000
trig            55000
clr             53000
target          1

[MGAME-MONITOR-GPU]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          gpu
polling         1000
trig            51000    53000    55000
clr             49000    51000    53000
target          1        2        3

[MGAME-MONITOR-TIMER_SOFTBANK]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          timer_softbank
polling         10000
trig            46000	52000	57000
clr             42000	48000	54000
target          470	4	1
