[VIRTUAL-SENSOR]
algo_type       virtual
sensors         quiet-therm-usr
weight          1
polling         1000

[SS-CPU0]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1708800  1478400  1324800

[SS-CPU1]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu1
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1708800  1478400  1324800

[SS-CPU2]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu2
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1708800  1478400  1324800

[SS-CPU3]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu3
polling         500
trig            49000            51000            53000
clr             47000             49000             51000
target          1708800  1478400  1324800

[SS-CPU4]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu4
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1708800  1478400  1324800

[SS-CPU5]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu5
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1708800  1478400  1324800

[SS-CPU6]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu6
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1804800  1651200  1401600

[SS-CPU7]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu7
polling         500
trig            48000            50000            52000
clr             46000             48000             50000
target          1804800  1651200  1401600

[MONITOR-BAT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          battery
polling         1000
trig            38000  39000  40000  41000  42000  43000  44000  45000  46000  47000  48000  49000
clr             37000  38000  39000  40000  41000  42000  43000  44000  45000  46000  47000  48000
target          0113   0214   0315   0416   0517   0618   0719   0820   0921   1022   1123   1224

