[NAV-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		1000
trig		46000		48000		50000		52000
clr		44000		46000		49000		51000
target		1451000 	1335000 	902000		500000

[NAV-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		2000
trig		42000		44000		46000		47000		48000		49000		51000		52000
clr		41000		42000		44000		46000		47000		48000		49000		51000
target		2292000 	2127000 	1820000 	1745000 	1632000 	1370000		921000		500000

[NAV-MONITOR-BAT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          battery
polling         2000
trig            35000   36800   38000   39000   39700   40400   41100   41800   43000   45000
clr             34000   35000   36800   38000   39000   39700   40400   41100   41800   43000
target          300     502     704     904     1105    1206    1207    1409    1411    1515

[NAV-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		45000		47000		49000		54000
clr		43000		45000		48000		53000
target		10100000	20100000	12400001	12500001

[NAV-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling		2000
trig		55000
clr		53000
target		1+1+1+1

[NAV-MONITOR-FLASH]
algo_type	monitor
sensor		flash_therm
device		temp_state
polling		2000
trig		53000
clr		51000
target		10100004

[NAV-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		55000
clr		52000
target		1

[NAV-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		2000
trig		5
clr		6
target		1286400+1+1
reverse		1

[NAV-MONITOR-CPU]
algo_type       monitor
sensor          CPU_SOC
device          hotplug_cpu6+hotplug_cpu7
polling         2000
trig            105000
clr             95000
target          1+1

[NAV-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		47000		49000		51000
clr		45000		47000		49000
target		0         1        2

[NAV-MONITOR-HBM]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          thermal_hbm_disabled
polling         2000
trig            39000
clr             38000
target          1

[NAV-MONITOR-BACKLIGHT_CTRL]
algo_type       monitor
sensor          VIRTUAL_LCD-SENSOR
device          mtk-cl-backlight
polling         2000
trig            41000   43000   46000
clr             39000   41000   43000
target          86      70      56

[NAV-MONITOR-MODEM]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          mtk-cl-scg-off
polling         2000
trig            49000
clr             48000
target          1
