[MGAME-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		2000
trig		47000		49000
clr		46000		48000
target		1258000	500000

[MGAME-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		2000
trig		47000		49000
clr		46000		48000
target		1258000	500000

[MGAME-MONITOR-BAT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          battery
polling         2000
trig            35000   36800   38000   39000   39700   40400   41100   41800   43000   45000
clr             34000   35000   36800   38000   39000   39700   40400   41100   41800   43000
target          300     502     704     904     905     906     1007    1409    1411    1515

[MGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		42000		44000		47000		54000
clr		40000		43000		46000		53000
target		10100000	20100000	12400001	12500001

[MGAME-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		50000
clr		48000
target		1

[MGAME-MONITOR-CHARGE_CONTROL]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          charge_control
polling         2000
trig            30000
clr             10000
target          1

[MGAME-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		6
target		1+1
reverse		1

[MGAME-MONITOR-CPU]
algo_type       monitor
sensor          CPU_SOC
device          hotplug_cpu6+hotplug_cpu7
polling         2000
trig            105000
clr             95000
target          1+1

[MGAME-MONITOR-HBM]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          thermal_hbm_disabled
polling         2000
trig            39000
clr             38000
target          1

[MGAME-MONITOR-BACKLIGHT_CTRL]
algo_type       monitor
sensor          VIRTUAL_LCD-SENSOR
device          mtk-cl-backlight
polling         2000
trig            41000   43000   46000
clr             39000   41000   43000
target          86      70      56

[MGAME-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		47000
clr		45000
target		20

[MGAME-MONITOR-MODEM]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          mtk-cl-scg-off
polling         2000
trig            49000
clr             48000
target          1
