[BAT_SOC]
algo_type	simulated
path		/sys/class/power_supply/battery/capacity
polling		20000

[CPU_SOC]
algo_type       simulated
path            /sys/class/thermal/thermal_zone4/temp
polling         20000


[VIRTUAL_LCD-SENSOR]
algo_type       virtual
sensors         lcd_therm
weight          1000
polling         2000
weight_sum      1000
compensation    1800

[VIRTUAL-SENSOR]
algo_type   	virtual
sensors		mtktsAP		battery		mtktsbtsmdpa	mtktsbtsnrpa	charger_therm		quiet_therm
weight		-76		199		-95		477		48			416
polling		2000
weight_sum	1000
compensation	500

[SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		2000
trig		20000		44000		45000		47000		49000
clr		19000		42000		44000		46000		48000
target		2100000 	1451000 	1335000 	902000		500000

[SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		2000
trig		20000		44000		45000		46000		48000		49000
clr		19000		43000		44000		45000		46000		48000
target		2100000 	1745000 	1632000 	1370000		921000		500000

[MONITOR-BAT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          battery
polling         2000
trig            35000   36800   38000   39000   39700   40400   41100   41800   43000   45000
clr             34000   35000   36800   38000   39000   39700   40400   41100   41800   43000
target          300     502     704     904     905     906     1007    1409    1411    1515

[MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		44000		47000		50000		54000
clr		42000		45000		49000		53000
target		10100000	20100000	12400001	12500001

[MONITOR-CCC]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          hotplug_cpu6+hotplug_cpu7
polling         2000
trig            55000
clr             53000
target          1+1

[MONITOR-FLASH]
algo_type       monitor
sensor          flash_therm
device          temp_state
polling         2000
trig            53000
clr             51000
target          10100004

[MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		55000
clr		52000
target		1

[MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		6
target		1+1
reverse		1

[MONITOR-CPU]
algo_type       monitor
sensor          CPU_SOC
device          hotplug_cpu6+hotplug_cpu7
polling         2000
trig            105000
clr             95000
target          1+1

[MONITOR-HBM]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          thermal_hbm_disabled
polling         2000
trig            39000
clr             38000
target          1

[MONITOR-BACKLIGHT_CTRL]
algo_type       monitor
sensor          VIRTUAL_LCD-SENSOR
device          mtk-cl-backlight
polling         2000
trig            41000	43000	46000
clr             39000	41000	43000
target          86	70	56

[MONITOR-MODEM]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          mtk-cl-scg-off
polling         2000
trig            49000
clr             48000
target          1
