[VIRTUAL-SENSOR]
algo_type       virtual
sensors         sdm-skin-therm-usr
weight          1
polling         1000

[SS-CPU0]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0
polling         500
trig            55000
clr             53000
target          691200
[SS-CPU6]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu6
polling         500
trig            55000
clr             53000
target          691200
[MONITOR-BAT]
algo_type       monitor
sensor          sdm-skin-therm-usr
device          battery
polling         1000
trig            32000  34000  36000  38000  40000  42000  44000  45000  47000
clr             30000  32000  34000  36000  38000  40000  42000  44000  45000
target          0904   1109   1311   1514   1715   1917   2119   2321   2421
[MONITOR-TEMP_STATE]
algo_type       monitor
sensor          xo-therm-usr
device          temp_state
polling         1000
trig            57000
clr             55000
target          5
[MONITOR-CL-BACKLIGHT]
algo_type       monitor
sensor          backlight_therm
device          backlight_therm
polling         1000
trig            42000    44000    46000    49000    51000
clr             40000    42000    44000    46000    49000
target          615      1434     1842     2457     3276
[MONITOR-BOOST_LIMIT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          boost_limit
polling         1000
trig            55000
clr             53000
target          1
[MONITOR-GPU]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          gpu
polling         1000
trig            51000   54000   57000
clr             48000   51000   54000
target          2       3       4
