[VIRTUAL-SENSOR]
algo_type       virtual
sensors         sdm-skin-therm-usr
weight          1
polling         1000

[SS-CPU0]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0
polling         500
trig            47000            48000            49000            50000            52000
clr             46000             47000             48000             49000             51000
target          1708800  1651200  1516800  1324800   940800
[SS-CPU6]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu6
polling         500
trig            47000            48000            49000            50000            51000            52000
clr             46000             47000             48000             49000             50000             51000
target          1804800  1651200  1516800  1401600  1228800   940800
[MONITOR-BAT]
algo_type       monitor
sensor          sdm-skin-therm-usr
device          battery
polling         1000
trig            34000  35000  36000  37500  39500  40000  41500  42000  44000  46000  47000  48000  49000
clr             32000  34000  35000  36000  37000  39500  40000  41500  42000  45500  46000  47000  48000
target          0504   0605   0807   1009   1211   1412   1513   1614   1817   1919   2121   2322   2423
[MONITOR-TEMP_STATE]
algo_type       monitor
sensor          xo-therm-usr
device          temp_state
polling         1000
trig            57000
clr             55000
target          5
[MONITOR-CL-BACKLIGHT]
algo_type       monitor
sensor          backlight_therm
device          backlight_therm
polling         1000
trig            42000    44000    46000    49000    51000
clr             40000    42000    44000    46000    49000
target          615      1434     1842     2457     3276
[MONITOR-BOOST_LIMIT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          boost_limit
polling         1000
trig            55000
clr             53000
target          1
[MONITOR-GPU]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          gpu
polling         1000
trig            49000            52000            55000
clr             46000             49000             52000
target          2       3       4
