[VIRTUAL-SENSOR]
algo_type       virtual
sensors         sdm-skin-therm-usr
weight          1
polling         1000

[SS-CPU0]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0
polling         500
trig            47000            49000            51000
clr             46000             47000             49000
target          1516800  1113600  940800
[SS-CPU6]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu6
polling         500
trig            47500            49500            51500
clr             46500             47500             49500
target          1804800  1401600  940800
[MONITOR-BAT]
algo_type       monitor
sensor          sdm-skin-therm-usr
device          battery
polling         1000
trig            35000  37000  39000  41000  43000  44000  46000  47000
clr             33000  35000  37000  39000  41000  43000  44000  45000
target          1511   1714   1915   2117   2219   2321   2422   2522
[MONITOR-TEMP_STATE]
algo_type       monitor
sensor          xo-therm-usr
device          temp_state
polling         1000
trig            49500    56000
clr             45500    51000
target          012300004  012300001

[MGAME-MONITOR-HOTPLUG_CTRL]
algo_type        monitor
sensor           VIRTUAL-SENSOR
device           hotplug_cpu3+hotplug_cpu7
polling          1000
trig             55000
clr              54000
target           1+1

[MONITOR-CL-BACKLIGHT]
algo_type       monitor
sensor          sdm-skin-therm-usr
device          backlight
polling         1000
trig            37000    42000    44000    47000
clr             36000    41000    42000    43000
target          1        340      736      1252
[MONITOR-BOOST_LIMIT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          boost_limit
polling         1000
trig            55000
clr             53000
target          1
[MONITOR-GPU]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          gpu
polling         1000
trig            49000            52000            55000
clr             46000             49000             52000
target          2       3       4
[MONITOR-modem]
algo_type       monitor
sensor          pa-therm0-usr
device          modem_pa_fr1
polling         1000
trig            39000   41000   47000
clr             37000   40000   45000
target          1       2       3
