[PHONE-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		2000
trig		38000		49000
clr		37000		48000
target		1537000 	437000

[PHONE-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		2000
trig		38000		49000
clr		37000		48000
target		2600000 	659000

[PHONE-MONITOR-BAT]
algo_type	monitor
sensor		CHARGER_VIRTUAL-SENSOR
device		battery
polling		2000
trig		15000	60000
clr		14000	48000
target		1414    1515

[PH0NE-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		44000		48000             52000       53000
clr		43000		46000             51000       52000
target		10100000	10100004          12400001    12500001

[PHONE-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		55000
clr		53000
target		1

[PHONE-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		6
target		1+1
reverse		1

[PHONE-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		48000		49000
clr		46000		48000
target		10	40

[PHONE-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		brightness0-clone
polling		2000
trig		37000	39000	42000	45000	47000	49000
clr		35000	37000	40000	43000	45000	47000
target		2048	4096	4914	5561	6761	7290

[PHONE-MONITOR-MODEM]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		mtk-cl-scg-off
polling		2000
trig		44000
clr		43000
target		1
