[NL-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		2000
trig		55000
clr		53000
target		700000

[NL-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		2000
trig		55000
clr		53000
target		921000

[NL-MONITOR-BAT]
algo_type	monitor
sensor		CHARGER_VIRTUAL-SENSOR
device		battery
polling		2000
trig		35000	36800	38000	39000	40000	42000	43000	46000	48000	60000
clr		34000	35000	36800	38000	39000	40000	42000	43000	46000	58000
target		301	402	504	705	907	1109	1210	1211	1412	1514

[NL-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		51000         53000
clr		49000         52000
target		12400001      12500001

[NL-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr		6
target		1+1
reverse		1

[NL-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		55000
clr		53000
target		20

[NL-MONITOR-BACKLIGHT_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		mtk-cl-backlight
polling		2000
trig		43000
clr		41000
target		90
