KERNEL_PATH := $(DEVICE_PATH)-kernel

# Kernel
TARGET_NO_KERNEL_OVERRIDE := true
BOARD_PREBUILT_DTBIMAGE_DIR := $(KERNEL_PATH)/dtb
BOARD_PREBUILT_DTBOIMAGE := $(KERNEL_PATH)/dtbo.img

PRODUCT_COPY_FILES += \
	$(KERNEL_PATH)/kernel:kernel

# Kernel modules
BOARD_KERNEL_MODULE_DIRS := 5.4-gki
BOARD_VENDOR_RAMDISK_KERNEL_MODULES := \
    $(KERNEL_PATH)/modules/focaltech_touch.ko \
    $(KERNEL_PATH)/modules/goodix_core.ko \
    $(KERNEL_PATH)/modules/hwid.ko \
    $(KERNEL_PATH)/modules/msm_drm.ko \
    $(KERNEL_PATH)/modules/xiaomi_touch.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD := $(BOARD_VENDOR_RAMDISK_KERNEL_MODULES)
BOARD_VENDOR_KERNEL_MODULES := $(wildcard $(KERNEL_PATH)/modules/*.ko)
BOARD_VENDOR_KERNEL_MODULES_LOAD := $(BOARD_VENDOR_KERNEL_MODULES)
BOARD_VENDOR_KERNEL_MODULES_5.4-gki := $(wildcard $(KERNEL_PATH)/modules/5.4-gki/*.ko)
BOARD_VENDOR_KERNEL_MODULES_LOAD_5.4-gki := $(BOARD_VENDOR_KERNEL_MODULES_5.4-gki)