/*
 * Copyright (C) 2026 FebriCahyaa. All rights reserved.
 *
 * HiCo Thermal is proprietary software. Use is governed by EULA.md;
 * copying, redistribution or modification without written permission
 * from the author is prohibited.
 */

// GENERATED by tools/gen_device_db.py from devices/xiaomi/*.prop. Do not edit:
// run the "Update Xiaomi device profiles" workflow or the generator instead.

#include "DeviceDatabase.hpp"

#include <array>

namespace hico::device_db {

namespace {

using namespace std::string_view_literals;

constexpr std::array<DeviceRecord, 0> kRecords{{
}};

} // namespace

std::span<const DeviceRecord> records() {
    return kRecords;
}

std::string_view generated_from() {
    return "dumps.tadiphone.dev/dumps/xiaomi (0 devices)"sv;
}

} // namespace hico::device_db
