[BAT_SOC]
algo_type	simulated
path		/sys/class/power_supply/battery/capacity
polling		10000

[VIRTUAL-SENSOR]
algo_type	virtual
sensors         battery     quiet_therm       charger_therm0    xo_therm
weight          547         191               -137              319
polling		1000
weight_sum      1000
compensation    2771

[ABT-SENSOR]
algo_type       ambient
sensors         conn_therm      quiet_therm
coefficient_a   855             989
coefficient_b   -845            -979
compensation    -14000          -10000
polling         10000
weight_sum      10

[INDIA-SS-CPU4]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu4
polling		1000
trig		43000		45000		47000		49000		50000		55000
clr		41000		43000		45000		47000		49000		51000
target		1862400		1670400		1478400 	1056000	    940800	710400

[INDIA-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		1000
trig		43000		45000		47000		49000		50000		55000
clr		41000		43000		45000		47000		49000		51000
target		1862400		1632000		1401600		1075200	    960000      844800

[INDIA-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig		35000	37000	38000   39000	41000	43000	45000	46000   48000   60000
clr		33000	35000	37000	38000   39000	41000	43000	45000   46000   48000
target		400	601	701     803	903	1207	1307	1310    1312    1515

[INDIA-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		45000		50000          53000
clr		44000		48000          51000
target		10100000	10100004       12400001

[INDIA-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling		2000
trig		55000
clr		53000
target		1+1+1+1

[INDIA-MONITOR-FLASH]
algo_type	monitor
sensor		flash_therm
device		temp_state
polling		2000
trig		53000
clr		51000
target		10100004

[INDIA-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		55000
clr		52000
target		1

[INDIA-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		2000
trig		5
clr		6
target		1286400+1+1
reverse		1

[INDIA-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		2000
trig		47000		49000		51000
clr		45000		47000		49000
target		0         1        2

[INDIA-MONITOR-HBM]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          thermal_hbm_disabled
polling         2000
trig            40000
clr             38000
target          1

[INDIA-MONITOR-BACKLIGHT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          backlight
polling         2000
trig            43000
clr             40000
target          573

[INDIA-MODEM-UL]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          modem_ul
polling         2000
trig            48000
clr             43000
target          1

[INDIA-MODEM-DL]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          modem_dl
polling         2000
trig            48000
clr             43000
target          1
