[INDIA-NL-SS-CPU0]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu0
polling		1000
trig        55000
clr         53000
target      672000

[INDIA-NL-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		1000
trig        55000
clr         53000
target      691200

[INDIA-NL-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		55000
clr			50000
target		2

[INDIA-NL-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		2000
trig		53000
clr			50000
target		1

[INDIA-NL-MONITOR-CL-BACKLIGHT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          backlight_therm
polling         2000
trig            38000    40000    42000
clr             36000    38000    40000
target          74       114      139

[INDIA-NL-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig        35000  37000  39000  41000
clr         32000  35000  37000  39000
target      2016   2520   3024   3528

[INDIA-NL-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		2000
trig		54000
clr			52000
target		10100004

[INDIA-NL-MONITOR-5G_TO_4G]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          modem_limit
polling         2000
trig            45000
clr             43000
target          1

[INDIA-NL-MONITOR-HOTPLUG_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu5+hotplug_cpu6
polling		2000
trig		55000
clr			50000
target		1+1

[INDIA-NL-MONITOR-BCL]
algo_type	monitor
sensor		bat_soc
device		hotplug_cpu6+hotplug_cpu7
polling		2000
trig		5
clr			6
target		1+1
reverse		1
