#!/usr/bin/env python3
#
# Copyright (C) 2026 FebriCahyaa. All rights reserved.
#
# HiCo Thermal is proprietary software. Use is governed by EULA.md;
# copying, redistribution or modification without written permission
# from the author is prohibited.
#
"""Compile devices/xiaomi/*.prop into hicod's device table.

The .prop files (written by tools/xiaomi_devices.py from firmware dumps) are
repository data only; they never ship in the module. This script turns them
into jni/src/XiaomiDevices.gen.cpp, which is compiled into hicod:

    python3 tools/gen_device_db.py            # regenerate
    python3 tools/gen_device_db.py --check    # CI: fail if the table is stale

Output is deterministic (sorted, no timestamps), so the generated file only
changes when the data does. Every value is validated here: codenames and
service names against their character sets, other fields reduced to
printable ASCII and escaped for C++.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "devices" / "xiaomi"
OUTPUT = ROOT / "jni" / "src" / "XiaomiDevices.gen.cpp"
SOURCE_DESC = "dumps.tadiphone.dev/dumps/xiaomi"

CODENAME_RE = re.compile(r"^[a-z0-9_]{1,64}$")
SERVICE_RE = re.compile(r"^[A-Za-z0-9_.@-]{1,96}$")
CONFIG_RE = re.compile(r"^[A-Za-z0-9_.-]{1,128}$")
FIELDS = ("brand", "model", "platform", "android", "source")
LIMITS = {"source": 512}

HEADER = """\
/*
 * Copyright (C) 2026 FebriCahyaa. All rights reserved.
 *
 * HiCo Thermal is proprietary software. Use is governed by EULA.md;
 * copying, redistribution or modification without written permission
 * from the author is prohibited.
 */

// GENERATED by tools/gen_device_db.py from devices/xiaomi/*.prop. Do not edit:
// run the "Update Xiaomi device profiles" workflow or the generator instead.
"""


def cxx_string(value: str) -> str:
    out = []
    for ch in value:
        if ch in '\\"':
            out.append("\\" + ch)
        elif " " <= ch <= "~":
            out.append(ch)
        # anything else was already filtered out by clean()
    return '"' + "".join(out) + '"sv'


def clean(value: str, limit: int = 128) -> str:
    return "".join(ch for ch in value if " " <= ch <= "~").strip()[:limit]


def parse(path: Path) -> dict:
    props: dict[str, str] = {}
    for line in path.read_text(errors="replace").splitlines():
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        props[key.strip()] = value.strip()

    codename = props.get("codename", "")
    if not CODENAME_RE.match(codename) or path.stem != codename:
        raise ValueError(f"{path.name}: codename '{codename}' is invalid or does not match the file name")

    record = {"codename": codename}
    for f in FIELDS:
        record[f] = clean(props.get(f, ""), LIMITS.get(f, 128))
    record["services"] = sorted({s for s in props.get("thermal_services", "").split(",") if SERVICE_RE.match(s)})
    record["configs"] = sorted({c for c in props.get("thermal_configs", "").split(",") if CONFIG_RE.match(c)})
    return record


def load(data_dir: Path) -> list[dict]:
    records = [parse(p) for p in sorted(data_dir.glob("*.prop"))]
    return sorted(records, key=lambda r: r["codename"])


def render(records: list[dict]) -> str:
    lines = [HEADER, '#include "DeviceDatabase.hpp"', "", "#include <array>", "", "namespace hico::device_db {", "",
             "namespace {", "", "using namespace std::string_view_literals;", ""]

    for i, r in enumerate(records):
        for kind in ("services", "configs"):
            if r[kind]:
                items = ", ".join(cxx_string(v) for v in r[kind])
                lines.append(f"constexpr std::array<std::string_view, {len(r[kind])}> k{kind.title()}{i}{{{items}}};")
    if records:
        lines.append("")

    lines.append(f"constexpr std::array<DeviceRecord, {len(records)}> kRecords{{{{")
    for i, r in enumerate(records):
        svc = f"k{'Services'}{i}" if r["services"] else "std::span<const std::string_view>{}"
        cfg = f"k{'Configs'}{i}" if r["configs"] else "std::span<const std::string_view>{}"
        fields = ", ".join(cxx_string(r[f]) for f in ("codename", *FIELDS))
        lines.append(f"    DeviceRecord{{{fields}, {svc}, {cfg}}},")
    lines += ["}};", "", "} // namespace", "",
              "std::span<const DeviceRecord> records() {", "    return kRecords;", "}", "",
              "std::string_view generated_from() {",
              f"    return {cxx_string(f'{SOURCE_DESC} ({len(records)} devices)')};", "}", "",
              "} // namespace hico::device_db", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", default=str(DATA_DIR), help="directory with <codename>.prop files")
    ap.add_argument("--output", default=str(OUTPUT), help="generated C++ file")
    ap.add_argument("--check", action="store_true", help="exit 1 if the generated file is out of date")
    args = ap.parse_args()

    try:
        text = render(load(Path(args.data)))
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    out = Path(args.output)
    if args.check:
        if not out.exists() or out.read_text() != text:
            print(f"{out} is out of date: run python3 tools/gen_device_db.py", file=sys.stderr)
            return 1
        print(f"{out} is up to date")
        return 0
    out.write_text(text)
    print(f"wrote {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
