#!/usr/bin/env python3
#
# Copyright (C) 2026 FebriCahyaa. All rights reserved.
#
# HiCo Thermal is proprietary software. Use is governed by EULA.md;
# copying, redistribution or modification without written permission
# from the author is prohibited.
#
"""Generate HiCo's Xiaomi device profiles from public firmware dumps.

Every profile is derived from the stock vendor partition of a real firmware
dump; nothing is typed in by hand. For each device it records:

  - identity: codename, brand, model / market name, SoC platform, Android release
  - thermal services declared in the vendor's thermal init scripts (exact names)
  - thermal configuration files shipped in vendor/etc (mi_thermald scenes, ...)
  - where it came from (dump URL and branch), so every line can be checked

Sources:
  --gitlab URL --group dumps/xiaomi   GitLab instance (default: dumps.tadiphone.dev)
  --local DIR                         directory of dump checkouts, one per device

Output (--out, default: repository root):
  devices/xiaomi/<codename>.prop      read by hicod (DeviceProfile)
  docs/DEVICES.md                     supported device list
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_GITLAB = "https://dumps.tadiphone.dev"
DEFAULT_GROUP = "dumps/xiaomi"

CODENAME_RE = re.compile(r"^[a-z0-9_]{1,64}$")
SERVICE_RE = re.compile(r"^[A-Za-z0-9_.@-]{1,96}$")
SERVICE_LINE_RE = re.compile(r"^\s*service\s+(\S+)\s+(\S+)")
THERMAL_CONFIG_RE = re.compile(r"^(thermal[\w.-]*\.(conf|xml|json)|thermal_info_config[\w.-]*\.json)$", re.I)
THERMAL_RC_RE = re.compile(r"thermal", re.I)
PRINTABLE_RE = re.compile(r"[^\x20-\x7e]")

# build.prop files, most specific first; the first file that defines a key wins.
BUILD_PROPS = ["vendor/build.prop", "product/etc/build.prop", "product/build.prop", "system/system/build.prop"]
PROP_KEYS = {
    "codename": ["ro.product.vendor.device", "ro.product.device", "ro.product.product.device"],
    "brand": ["ro.product.vendor.brand", "ro.product.brand", "ro.product.product.brand"],
    "market": ["ro.product.marketname", "ro.product.product.marketname", "ro.product.vendor.marketname"],
    "model": ["ro.product.vendor.model", "ro.product.model", "ro.product.product.model"],
    "platform": ["ro.board.platform", "ro.vendor.qti.soc_name", "ro.hardware"],
    "android": ["ro.vendor.build.version.release", "ro.build.version.release"],
}


@dataclass
class Device:
    codename: str
    brand: str = ""
    model: str = ""
    platform: str = ""
    android: str = ""
    source: str = ""
    services: list[str] = field(default_factory=list)
    configs: list[str] = field(default_factory=list)
    mi_thermald: bool = False

    def to_prop(self) -> str:
        lines = [
            "# Generated by tools/xiaomi_devices.py from the stock firmware dump below.",
            "# Do not edit by hand: re-run the generator instead.",
            f"codename={self.codename}",
            f"brand={clean(self.brand)}",
            f"model={clean(self.model)}",
            f"platform={clean(self.platform)}",
            f"android={clean(self.android)}",
            f"source={clean(self.source)}",
            f"mi_thermald={1 if self.mi_thermald else 0}",
            f"thermal_services={','.join(self.services)}",
            f"thermal_configs={','.join(self.configs)}",
        ]
        return "\n".join(lines) + "\n"


def clean(value: str) -> str:
    return PRINTABLE_RE.sub("", value).replace("=", " ").strip()[:128]


def parse_props(text: str) -> dict[str, str]:
    props: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        props.setdefault(key.strip(), value.strip())
    return props


def parse_rc_services(text: str) -> list[str]:
    names = []
    for line in text.splitlines():
        m = SERVICE_LINE_RE.match(line)
        if m and SERVICE_RE.match(m.group(1)):
            names.append(m.group(1))
    return names


# ── Sources ───────────────────────────────────────────────────────────────────


class LocalSource:
    """A directory holding one checked-out dump per device."""

    def __init__(self, root: str):
        self.root = Path(root)

    def projects(self) -> list[dict]:
        return [
            {"id": p.name, "path": p.name, "branch": "local", "url": str(p)}
            for p in sorted(self.root.iterdir())
            if p.is_dir() and not p.name.startswith(".")
        ]

    def read(self, project: dict, path: str) -> str | None:
        f = self.root / project["path"] / path
        try:
            return f.read_text(errors="replace") if f.is_file() else None
        except OSError:
            return None

    def listdir(self, project: dict, path: str) -> list[str]:
        d = self.root / project["path"] / path
        return sorted(p.name for p in d.iterdir() if p.is_file()) if d.is_dir() else []


class GitLabSource:
    """GitLab API (v4) of a firmware dump instance."""

    def __init__(self, base: str, group: str, limit: int | None):
        self.base = base.rstrip("/")
        self.group = group
        self.limit = limit

    def _get(self, url: str) -> tuple[bytes, dict] | None:
        for attempt in range(4):
            try:
                req = urllib.request.Request(url, headers={"User-Agent": "HiCo-Thermal-device-scanner"})
                with urllib.request.urlopen(req, timeout=30) as resp:
                    return resp.read(), dict(resp.headers)
            except urllib.error.HTTPError as e:
                if e.code == 404:
                    return None
                if e.code in (429, 500, 502, 503, 504):
                    time.sleep(2 ** attempt * 2)
                    continue
                raise
            except (urllib.error.URLError, TimeoutError):
                time.sleep(2 ** attempt * 2)
        raise RuntimeError(f"giving up on {url}")

    def _api(self, endpoint: str, **params) -> str:
        query = urllib.parse.urlencode(params)
        return f"{self.base}/api/v4/{endpoint}{'?' + query if query else ''}"

    def projects(self) -> list[dict]:
        group = urllib.parse.quote(self.group, safe="")
        out, page = [], 1
        while page:
            got = self._get(self._api(f"groups/{group}/projects", per_page=100, page=page,
                                      include_subgroups="true", archived="false", order_by="path", sort="asc"))
            if got is None:
                raise RuntimeError(f"group {self.group} not found on {self.base}")
            body, headers = got
            for p in json.loads(body):
                if p.get("empty_repo") or not p.get("default_branch"):
                    continue
                out.append({
                    "id": p["id"],
                    "path": p["path"],
                    "branch": p["default_branch"],
                    "url": f"{p['web_url']}/-/tree/{p['default_branch']}",
                })
                if self.limit and len(out) >= self.limit:
                    return out
            page = int(headers.get("X-Next-Page") or headers.get("x-next-page") or 0)
        return out

    def read(self, project: dict, path: str) -> str | None:
        file = urllib.parse.quote(path, safe="")
        got = self._get(self._api(f"projects/{project['id']}/repository/files/{file}/raw", ref=project["branch"]))
        return got[0].decode(errors="replace") if got else None

    def listdir(self, project: dict, path: str) -> list[str]:
        names, page = [], 1
        while page:
            got = self._get(self._api(f"projects/{project['id']}/repository/tree", path=path,
                                      ref=project["branch"], per_page=100, page=page))
            if got is None:
                return names
            body, headers = got
            names += [e["name"] for e in json.loads(body) if e.get("type") == "blob"]
            page = int(headers.get("X-Next-Page") or headers.get("x-next-page") or 0)
        return sorted(names)


# ── Scan ─────────────────────────────────────────────────────────────────────


def scan(source, project: dict) -> Device | None:
    props: dict[str, str] = {}
    for path in BUILD_PROPS:
        text = source.read(project, path)
        if text:
            for k, v in parse_props(text).items():
                props.setdefault(k, v)
    if not props:
        return None

    def pick(name: str) -> str:
        return next((props[k] for k in PROP_KEYS[name] if props.get(k)), "")

    codename = pick("codename").lower()
    if not CODENAME_RE.match(codename):
        return None

    brand = pick("brand")
    dev = Device(
        codename=codename,
        brand=brand[:1].upper() + brand[1:] if brand else "Xiaomi",
        model=pick("market") or pick("model"),
        platform=pick("platform"),
        android=pick("android"),
        source=project["url"],
    )

    dev.configs = sorted({n for n in source.listdir(project, "vendor/etc") if THERMAL_CONFIG_RE.match(n)})

    services: set[str] = set()
    for rc in source.listdir(project, "vendor/etc/init"):
        if not rc.endswith(".rc") or not THERMAL_RC_RE.search(rc):
            continue
        text = source.read(project, f"vendor/etc/init/{rc}") or ""
        services.update(parse_rc_services(text))
    dev.services = sorted(services)
    dev.mi_thermald = any("mi_thermald" in s for s in dev.services)
    return dev


def write_outputs(devices: list[Device], out: Path, source_desc: str) -> None:
    ddir = out / "devices" / "xiaomi"
    ddir.mkdir(parents=True, exist_ok=True)
    for old in ddir.glob("*.prop"):
        old.unlink()
    for d in devices:
        (ddir / f"{d.codename}.prop").write_text(d.to_prop())

    rows = sorted(devices, key=lambda d: (d.brand.lower(), d.model.lower(), d.codename))
    lines = [
        "# Supported Xiaomi devices",
        "",
        "Generated by [`tools/xiaomi_devices.py`](../tools/xiaomi_devices.py) from the stock vendor",
        f"partitions in {source_desc}. Every row links to the dump it was read from.",
        "",
        "HiCo also runs on devices that are not listed: it then relies on runtime detection only",
        "(thermal services from `init.svc.*`, zones and cooling devices from `/sys/class/thermal`).",
        "A profile adds the exact thermal service names the vendor declares in its init scripts.",
        "",
        f"**{len(rows)} devices**",
        "",
        "| Device | Codename | Platform | Android | mi_thermald | Thermal services | Thermal configs | Source |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for d in rows:
        services = ", ".join(f"`{s}`" for s in d.services) or "–"
        lines.append(
            f"| {clean(d.brand)} {clean(d.model)} | `{d.codename}` | {clean(d.platform) or '–'} | "
            f"{clean(d.android) or '–'} | {'yes' if d.mi_thermald else 'no'} | {services} | "
            f"{len(d.configs)} | [dump]({d.source}) |"
        )
    (out / "docs").mkdir(exist_ok=True)
    (out / "docs" / "DEVICES.md").write_text("\n".join(lines) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    src = ap.add_mutually_exclusive_group()
    src.add_argument("--gitlab", default=DEFAULT_GITLAB, help="GitLab instance URL")
    src.add_argument("--local", help="directory of dump checkouts (one per device)")
    ap.add_argument("--group", default=DEFAULT_GROUP, help="GitLab group holding the Xiaomi dumps")
    ap.add_argument("--out", default=str(Path(__file__).resolve().parent.parent), help="repository root")
    ap.add_argument("--limit", type=int, help="scan at most N projects (testing)")
    ap.add_argument("--jobs", type=int, default=8)
    args = ap.parse_args()

    if args.local:
        source, desc = LocalSource(args.local), "local dumps"
    else:
        source = GitLabSource(args.gitlab, args.group, args.limit)
        desc = f"[{args.group}]({args.gitlab.rstrip('/')}/{args.group})"

    projects = source.projects()
    if args.limit:
        projects = projects[: args.limit]
    print(f"scanning {len(projects)} dumps", file=sys.stderr)

    devices: dict[str, Device] = {}
    failures = 0
    with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, args.jobs)) as pool:
        futures = {pool.submit(scan, source, p): p for p in projects}
        for fut in concurrent.futures.as_completed(futures):
            p = futures[fut]
            try:
                dev = fut.result()
            except Exception as e:  # keep going: one broken dump must not stop the scan
                failures += 1
                print(f"  ! {p['path']}: {e}", file=sys.stderr)
                continue
            if dev is None:
                print(f"  - {p['path']}: no usable vendor build.prop, skipped", file=sys.stderr)
                continue
            # Several dumps can share a codename (regional variants): keep the richest one.
            prev = devices.get(dev.codename)
            if prev is None or (len(dev.services), len(dev.configs)) > (len(prev.services), len(prev.configs)):
                devices[dev.codename] = dev

    write_outputs(list(devices.values()), Path(args.out), desc)
    print(f"{len(devices)} device profiles written, {failures} dumps failed", file=sys.stderr)
    return 1 if failures and not devices else 0


if __name__ == "__main__":
    sys.exit(main())
