[BAT_SOC]
algo_type	simulated
path	/sys/class/power_supply/battery/capacity
polling	2000

[VIRTUAL-SENSOR]
algo_type	Virtual
sensors         mtktsAP         mtkcsCPU      mtktsbtsmdpa mtktscharger battery
weight          56              316           250          70           231
polling		2000
weight_sum	1000
compensation    928

[SS-CPU0]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0
polling         2000
trig	        39000	        41000	        43000	        45000	        47000	        49000	        51000	        53000
clr	        37000	        39000	        41000	        43000	        45000	        47000	        49000	        51000
target          1916000	1750000	1645000	1393000 1128000	1048000 862000	650000

[SS-CPU6]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu6
polling         2000
trig	        39000	        41000	        43000	        45000	        47000	        49000	        51000	        53000
clr	        37000	        39000	        41000	        43000	        45000	        47000	        49000	        51000
target	        1993000	1837000 1650000 1418000 1274000 1042000 985000  898000

[MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		2000
trig	        32000	34000	37500	39000	40000	41500	43000	46000
clr	        30000	32000	35000	37000	39000	40000	41500	43000
target	        500	601	803	1004	1005	1008	1414	1515

[MONITOR-TEMP_STATE]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          temp_state
polling         2000
trig	        45000      48000      51000      53000
clr	        43000      46000      50000      51000
target	        10100000   10300004   12310004   12520004

[MONITOR-CCC]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          hotplug_cpu0+hotplug_cpu1+hotplug_cpu6
polling         2000
trig            55000
clr             53000
target          1+1+1

[MONITOR-BOOST_LIMIT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          boost_limit
polling         2000
trig            53000
clr             50000
target          1

[MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	gpu
polling	2000
trig	46000	48000	50000
clr	44000	46000	48000
target	0	1	2

[MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	market_download_limit
polling	2000
trig	40000
clr	37000
target	1

[MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	thermal_max_brightness
polling	2000
trig	51000
clr	49000
target	160

[MONITOR-5G TO 4G]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	modem_limit
polling	2000
trig	45000
clr	43000
target	1

