[CGAME-SS-CPU0]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu0
polling	2000
trig	48000	49000	50000
clr	47000	48000	49000
target	1750000	1287000	650000

[CGAME-SS-CPU6]
algo_type	ss
sensor	VIRTUAL-SENSOR
device	cpu6
polling	2000
trig	48000	49000	50000
clr	47000	48000	49000
target	1993000	1418000	840000

[CGAME-MONITOR-BAT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	battery
polling	2000
trig	32000	35000	36000	37000	39000	41000
clr	30000	34000	35000	36000	38000	39000
target	600	701	803	909	1010	1414

[CGAME-MONITOR-TEMP_STATE]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	temp_state
polling	2000
trig	15000      48000      51000      53000
clr	13000      46000      50000      51000
target	10100000   10300004   12310004   12520004

[CGAME-MONITOR-CCC]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	hotplug_cpu0+hotplug_cpu1+hotplug_cpu6
polling	2000
trig	55000
clr	53000
target	1+1+1

[CGAME-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	boost_limit
polling	2000
trig	55000
clr	53000
target	1

[CGAME-MONITOR-GPU]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	gpu
polling	2000
trig	51000
clr	49000
target	2

[CGAME-MONITOR-BACKLIGHT]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	thermal_max_brightness
polling	2000
trig	51000
clr	49000
target	160

[CGAME-MONITOR-PARALLEL-TO-SERIAL]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	market_download_limit
polling	2000
trig	40000
clr	37000
target	1

[CGAME-MONITOR-5G TO 4G]
algo_type	monitor
sensor	VIRTUAL-SENSOR
device	modem_limit
polling	2000
trig	45000
clr	43000
target	1

