[CAMERA-SS-CPU6]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu6
polling		500
trig		42000		46000		49000		55000
clr		41000		45000		48000		54000
target		1843200		1555200		1324800		806400

[CAMERA-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		1000
trig		35000	38000	40000	42000	60000
clr		34000	37000	39000	41000	48000
target		900	1000	1302    1410    1515

[CAMERA-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		1000
trig		50000		53000
clr		48000		51000
target		2400004		2100001

[CAMERA-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		1000
trig		55000
clr		52000
target		1

[CAMERA-MONITOR-BCL]
algo_type	monitor
sensor		bat_soc
device		hotplug_cpu6+hotplug_cpu7
polling		1000
trig		5
clr		6
target		1+1
reverse		1

[CAMERA-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		1000
trig		48000		50000		53000
clr		46000		48000		50000
target		0	1	2

[CAMERA-MONITOR-CCC_CTRL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7+backlight
polling		1000
trig		50000
clr		48000
target		1+1+1+1+1500

[CAMERA-MONITOR-MODEM-LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		4g_modem_pa0+4g_modem_tsens
polling		1000
trig		51000
clr		48000
target		2+1
