[VIRTUAL-SENSOR]
algo_type        virtual
sensors          mtktsAP
weight           1
polling          1000

[SS-CPU0]
algo_type        ss
sensor           VIRTUAL-SENSOR
device           cpu0
polling          1000
trig             46000             47000             48000             49000             50000             51000             52000             54000
clr              45000              46000              47000              48000              49000              50000              51000              52000
target           1933000  1866000  1800000  1733000  1375000  1375000  1075000  500000

[SS-CPU6]
algo_type        ss
sensor           VIRTUAL-SENSOR
device           cpu6
polling          1000
trig             46000             47000             48000             49000             50000             51000             52000             54000
clr              45000              46000              47000              48000              49000              50000              51000              52000
target           1986000  1923000  1860000  1796000  1419000  1419000  1085000  774000

[MONITOR-GPU]
algo_type        monitor
sensor           VIRTUAL-SENSOR
device           gpu
polling          1000
trig             45000   50000   55000
clr              40000   45000   50000
target           10      15      20

[MONITOR-BOOST_LIMIT]
algo_type        monitor
sensor           VIRTUAL-SENSOR
device           boost_limit
polling          2000
trig             54000
clr              52000
target           1

[MONITOR-MTK-CL-BACKLIGHT]
algo_type        monitor
sensor           VIRTUAL-SENSOR
device           mtk-cl-backlight
polling          2000
trig             40000  42000  44000  46000
clr              38000  40000  42000  44000
target           85     75     65     55

[MONITOR-BAT]
algo_type        monitor
sensor           mtktsAP
device           battery
polling          2000
trig             34000  35000  36000  37000  39000  40000  41500  42000  44000  46000  47000  48000  49000
clr              32000  34000  35000  36000  37000  39000  40000  41500  42000  45500  46000  47000  48000
target           0504   0605   0807   1009   1211   1412   1513   1614   1817   1919   2121   2322   2423

[MONITOR-FLASH-TEMP_STATE]
algo_type        monitor
sensor           flash_therm
device           temp_state
polling          2000
trig             54000
clr              52000
target           10100004

[MONITOR-BATTERY-TEMP_STATE]
algo_type        monitor
sensor           battery
device           temp_state
polling          2000
trig             42000  48000
clr              38000  46000
target           10100000  10300001

[MONITOR-HOTPLUG_CTRL]
algo_type        monitor
sensor           VIRTUAL-SENSOR
device           hotplug_cpu5+hotplug_cpu6
polling          2000
trig             60000
clr              55000
target           1+1

[MONITOR-BCL]
algo_type        monitor
sensor           bat_soc
device           hotplug_cpu6+hotplug_cpu7
polling          2000
trig             5
clr              6
target           1+1
reverse          1
