[VIRTUAL-SENSOR]
algo_type        virtual
sensors          mtktsAP
weight           1
polling          1000

[NAVG-SS-CPU0]
algo_type        ss
sensor           VIRTUAL-SENSOR
device           cpu0
polling          1000
trig             40000             41000             43000             45000             46000             47000             48000             49000
clr              39000              40000              41000              43000              45000              46000              47000              48000
target           1375000  1275000  1175000  1075000  975000  875000  774000  500000

[NAVG-SS-CPU6]
algo_type        ss
sensor           VIRTUAL-SENSOR
device           cpu6
polling          1000
trig             40000             41000             43000             45000             46000             47000             48000             49000
clr              39000              40000              41000              43000              45000              46000              47000              48000
target           1419000  1308000  1169000  1085000  1002000  919000  835000  774000

[NAVG-MONITOR-GPU]
algo_type        monitor
sensor           VIRTUAL-SENSOR
device           gpu
polling          1000
trig             45000   50000   55000
clr              40000   45000   50000
target           10      15      20

[NAVG-MONITOR-BOOST_LIMIT]
algo_type        monitor
sensor           VIRTUAL-SENSOR
device           boost_limit
polling          2000
trig             52000
clr              49000
target           1

[NAVG-MONITOR-MTK-CL-BACKLIGHT]
algo_type        monitor
sensor           VIRTUAL-SENSOR
device           mtk-cl-backlight
polling          2000
trig             40000  42000  44000  46000
clr              38000  40000  42000  44000
target           85     75     65     55

[NAVG-MONITOR-BAT]
algo_type        monitor
sensor           mtktsAP
device           battery
polling          2000
trig             32000  37000  38000  39000  40000  41000  42000  43000  44000
clr              31000  36000  37000  38000  39000  40000  41000  42000  43000
target           2402   2402   2404   2405   2407   2409   2410   2412   2414

[NAVG-MONITOR-FLASH-TEMP_STATE]
algo_type        monitor
sensor           flash_therm
device           temp_state
polling          2000
trig             54000
clr              52000
target           10100004

[NAVG-MONITOR-BATTERY-TEMP_STATE]
algo_type        monitor
sensor           battery
device           temp_state
polling          2000
trig             52000
clr              50000
target           12300001

[NAVG-MONITOR-HOTPLUG_CTRL]
algo_type        monitor
sensor           VIRTUAL-SENSOR
device           hotplug_cpu5+hotplug_cpu6
polling          2000
trig             51000
clr              48000
target           1+1

[NAVG-MONITOR-BCL]
algo_type        monitor
sensor           bat_soc
device           hotplug_cpu6+hotplug_cpu7
polling          2000
trig             5
clr              6
target           1+1
reverse          1
