[VIRTUAL-SENSOR]
algo_type       virtual
sensors         quiet-therm-usr
weight          1
polling         1000

[VIRTUAL-SENSOR2]
algo_type       virtual
sensors         backlight_therm
weight          1
polling         1000

[SS-CPU0]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu0
polling         500
trig            50000            52000            54000
clr             48000             50000             52000
target          1612800  1420800  1305600
[SS-CPU1]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu1
polling         500
trig            50000            52000            54000
clr             48000             50000             52000
target          1612800  1420800  1305600

[SS-CPU2]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu2
polling         500
trig            50000            52000            54000
clr             48000             50000             52000
target          1612800  1420800  1305600

[SS-CPU3]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu3
polling         500
trig            50000            52000            54000
clr             48000             50000             52000
target          1612800  1420800  1305600

[SS-CPU4]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu4
polling         500
trig            50000            52000            54000
clr             48000             50000             52000
target          1804800  1612800  1536000

[SS-CPU5]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu5
polling         500
trig            50000            52000            54000
clr             48000             50000             52000
target          1804800  1612800  1536000

[SS-CPU6]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu6
polling         500
trig            50000            52000            54000
clr             48000             50000             52000
target          1804800  1612800  1536000

[SS-CPU7]
algo_type       ss
sensor          VIRTUAL-SENSOR
device          cpu7
polling         500
trig            50000            52000            54000
clr             48000             50000             52000
target          1804800  1612800  1536000

[TGEME-MONITOR-BAT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          battery
polling         1000
trig            38000   39000   40000   41000   42000   43000   44000  45000  46000
clr             37000   38000   39000   40000   41000   42000   43000  44000  45000
target          0110    0211    0312    0413    0514    0615    0716   0817   0918

[TGAME-MONITOR-TEMP_STATE]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          temp_state
polling         1000
trig            60000
clr             58000
target          5

[TGAME-MONITOR-CL-BACKLIGHT]
algo_type       monitor
sensor          VIRTUAL-SENSOR2
device          backlight
polling         1000
trig            42000    44000    46000
clr             40000    42000    44000
target          2867     2662     2457

[TGAME-MONITOR-BOOST_LIMIT]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          boost_limit
polling         1000
trig            55000
clr             53000
target          1

[TGAME-MONITOR-GPU]
algo_type       monitor
sensor          VIRTUAL-SENSOR
device          gpu
polling         1000
trig            51000    53000    55000
clr             49000    51000    53000
target          2        4        6



