# SENSOR : ALIAS

debug
#Conf file: /vendor/etc/thermal-engine.conf

[SS-CPU]
algo_type ss
sampling 1000
sensor quiet-therm-usr
device cpu0
set_point 47000
set_point_clr 44000
time_constant 0
device_max_limit 614000

[SS-GPU-SKIN-TEMP]
algo_type ss
sampling 10000
sensor quiet-therm-usr
device gpu
set_point 48000
set_point_clr 44000
time_constant 0
device_max_limit 400000000

[SS_GPU]
algo_type ss
sampling 250
sensor gpu-usr
device gpu
set_point 85000
set_point_clr 65000
time_constant 0

[MONITOR_QUIET_THERM_HOTPLUG]
algo_type monitor
sampling 1000
sensor quiet-therm-usr
thresholds 46000 48000
thresholds_clr 43000 45000
actions hotplug_2+hotplug_3 hotplug_2+hotplug_3
action_info 0+1 1+1

[CPU-MONITOR]
algo_type monitor
sampling 5000
sensor sdm-skin-therm-usr
thresholds 52000
thresholds_clr 50000
actions shutdown
action_info 5000

[BATTERY_CHARGING_CTL]
algo_type monitor
sampling 5000
sensor quiet-therm-usr
thresholds 41000 43000
thresholds_clr 40000 42000
actions battery battery
action_info 2 3

[SKIN_CHARGING_CTL]
algo_type monitor
sampling 5000
sensor sdm-skin-therm-usr
thresholds 43000 45000
thresholds_clr 42000 44000
actions battery battery
action_info 4 5

