[PHONE-SS-CPU7]
algo_type	ss
sensor		VIRTUAL-SENSOR
device		cpu7
polling		2000
trig		33000		54000
clr		31000		51000
target		1305600		844800

[PHONE-MONITOR-BAT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		battery
polling		10000
trig		5000                20000		60000
clr		3000                18000		48000
target		300                 1313		1515

[PHONE-MONITOR-TEMP_STATE]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		temp_state
polling		10000
trig		45000		46500		52000
clr		43000		45000		50000
target		10100000	10100004	12400001

[PHONE-MONITOR-CCC]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		hotplug_cpu4+hotplug_cpu5+hotplug_cpu6+hotplug_cpu7
polling		10000
trig		55000
clr		53000
target		1+1+1+1

[PHONE-MONITOR-BOOST_LIMIT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		boost_limit
polling		10000
trig		54000
clr		51000
target		1

[PHONE-MONITOR-BCL]
algo_type	monitor
sensor		BAT_SOC
device		cpu4+hotplug_cpu5+hotplug_cpu6
polling		10000
trig		5
clr		6
target		1286400+1+1
reverse		1

[PHONE-MONITOR-GPU]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		gpu
polling		10000
trig		47000		49000		51000
clr		45000		47000		49000
target		0		1		2

[PHONE-MONITOR-BACKLIGHT]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		backlight-clone
polling		10000
trig		37000		39000		41000		43000		46000
clr		35000		37000		39000		41000		43000
target		2048		4096		4914		6144		6761

[PHONE-MODEM-UL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_ul
polling		10000
trig		46000
clr		43000
target		1

[PHONE-MODEM-DL]
algo_type	monitor
sensor		VIRTUAL-SENSOR
device		modem_dl
polling		10000
trig		46000
clr		43000
target		1

